// Generated by vasnc from ASN.1 module `DEMO-Definitions`. Do not edit.
#![allow(non_snake_case, non_camel_case_types, unused_imports, unused_variables)]
#![allow(bindings_with_variant_name, unused_parens, unused_braces, unused_comparisons, dead_code)]
use vstd::prelude::*;
use vasn::bits::bitspec::*;
use vasn::uper::format::*;
use vasn::uper::prim::*;
use vasn::uper::term::*;
use vasn::uper::cursor::*;
use vasn::uper::opt::*;
use vasn::uper::list::*;
use vasn::uper::lendet::*;
use vasn::uper::frag::*;
use vasn::uper::fraglist::*;
use vasn::uper::intx::*;
use vasn::utf8::*;
use vasn::uper::opentype::*;
use vasn::uper::seqext::*;
use vasn::uper::fast::*;
use vasn::jer::*;
use vasn::arb::Gen;

verus! {

broadcast use {format_steps, map_steps, opt_steps, unit_steps, list_steps};

// ---------------------------------------------------------------- Alpha
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub enum Alpha {
    alpha0,
    alpha04,
    alpha05,
    alpha06,
    alpha07,
    alpha08,
    alpha09,
    alpha1,
}

pub open spec fn Alpha_to(v: u64) -> Alpha {
    if v == 0 { Alpha::alpha0 } else {
    if v == 1 { Alpha::alpha04 } else {
    if v == 2 { Alpha::alpha05 } else {
    if v == 3 { Alpha::alpha06 } else {
    if v == 4 { Alpha::alpha07 } else {
    if v == 5 { Alpha::alpha08 } else {
    if v == 6 { Alpha::alpha09 } else {
    Alpha::alpha1
    }
    }
    }
    }
    }
    }
    }
}

pub open spec fn Alpha_from(e: Alpha) -> u64 {
    match e {
        Alpha::alpha0 => 0,
        Alpha::alpha04 => 1,
        Alpha::alpha05 => 2,
        Alpha::alpha06 => 3,
        Alpha::alpha07 => 4,
        Alpha::alpha08 => 5,
        Alpha::alpha09 => 6,
        Alpha::alpha1 => 7,
    }
}

pub open spec fn Alpha_ok() -> spec_fn(u64) -> bool { |v: u64| v <= 7 }
pub open spec fn Alpha_to_f() -> spec_fn(u64) -> Alpha { |v: u64| Alpha_to(v) }
pub open spec fn Alpha_from_f() -> spec_fn(Alpha) -> u64 { |e: Alpha| Alpha_from(e) }
pub open spec fn Alpha_base_wf() -> Wf<u64> { restrict_wf(uint_wf(3), Alpha_ok()) }
pub open spec fn Alpha_base_dec() -> Dec<u64> { restrict_dec(uint_dec(3), Alpha_ok()) }
pub open spec fn Alpha_wf() -> Wf<Alpha> { map_wf(Alpha_base_wf(), Alpha_to_f(), Alpha_from_f()) }
pub open spec fn Alpha_enc() -> Enc<Alpha> { map_enc(uint_enc(3), Alpha_from_f()) }
pub open spec fn Alpha_dec() -> Dec<Alpha> { map_dec(Alpha_base_dec(), Alpha_to_f()) }

pub proof fn Alpha_is_format()
    ensures is_format(Alpha_wf(), Alpha_enc(), Alpha_dec()),
{
    lemma_uint_format(3);
    lemma_restrict_format(uint_wf(3), uint_enc(3), uint_dec(3), Alpha_ok());
    assert forall|v: u64| Alpha_base_wf()(v) implies
        #[trigger] Alpha_from_f()(Alpha_to_f()(v)) == v by { }
    lemma_map_format(Alpha_base_wf(), uint_enc(3), Alpha_base_dec(),
                     Alpha_to_f(), Alpha_from_f());
}

#[inline]
pub fn Alpha_of_u64(v: u64) -> (e: Alpha)
    requires v <= 7,
    ensures e == Alpha_to(v),
{
    if v == 0 { Alpha::alpha0 } else {
    if v == 1 { Alpha::alpha04 } else {
    if v == 2 { Alpha::alpha05 } else {
    if v == 3 { Alpha::alpha06 } else {
    if v == 4 { Alpha::alpha07 } else {
    if v == 5 { Alpha::alpha08 } else {
    if v == 6 { Alpha::alpha09 } else {
    Alpha::alpha1
    }
    }
    }
    }
    }
    }
    }
}

#[inline]
pub fn Alpha_as_u64(e: &Alpha) -> (v: u64)
    ensures v == Alpha_from(*e),
{
    match e {
        Alpha::alpha0 => 0,
        Alpha::alpha04 => 1,
        Alpha::alpha05 => 2,
        Alpha::alpha06 => 3,
        Alpha::alpha07 => 4,
        Alpha::alpha08 => 5,
        Alpha::alpha09 => 6,
        Alpha::alpha1 => 7,
    }
}

#[inline]
pub fn Alpha_decode(r: &mut BitReader) -> (res: Option<(Alpha, Flg)>)
    requires old(r).wf(),
    ensures
        final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Alpha_dec()(old(r).rem())
                == Some::<(Alpha, nat, Flg)>((v,
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => Alpha_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    match r.read_uint(3) {
        Some(v) => if v <= 7 {
            proof {
                lemma_restrict_dec_some(uint_dec(3), Alpha_ok(), start, v, 3, Flg::SameVer);
                lemma_map_dec_some(Alpha_base_dec(), Alpha_to_f(), start, v, 3, Flg::SameVer);
            }
            Some((Alpha_of_u64(v), Flg::SameVer))
        } else {
            proof {
                lemma_restrict_dec_none(uint_dec(3), Alpha_ok(), start);
                lemma_map_dec_none(Alpha_base_dec(), Alpha_to_f(), start);
            }
            { r.fail("ENUMERATED index (0..7)"); None }
        },
        None => {
            proof {
                lemma_restrict_dec_none(uint_dec(3), Alpha_ok(), start);
                lemma_map_dec_none(Alpha_base_dec(), Alpha_to_f(), start);
            }
            { r.fail("ENUMERATED index (0..7)"); None }
        }
    }
}

#[inline]
pub fn Alpha_encode(w: &mut BitWriter, e: &Alpha) -> (ok: bool)
    requires old(w).wf(),
    ensures
        final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Alpha_enc()(*e),
{
    let v = Alpha_as_u64(e);
    proof { assert(uint_wf(3 as nat)(v)) by { reveal_with_fuel(p2, 5); } }
    w.write_uint(3, v)
}

#[verifier::external]
#[inline]
pub fn Alpha_jer(v: &Alpha, o: &mut String) {
    match v {
        Alpha::alpha0 => jer_ident("alpha0", o),
        Alpha::alpha04 => jer_ident("alpha04", o),
        Alpha::alpha05 => jer_ident("alpha05", o),
        Alpha::alpha06 => jer_ident("alpha06", o),
        Alpha::alpha07 => jer_ident("alpha07", o),
        Alpha::alpha08 => jer_ident("alpha08", o),
        Alpha::alpha09 => jer_ident("alpha09", o),
        Alpha::alpha1 => jer_ident("alpha1", o),
    }
}

#[verifier::external]
#[inline]
pub fn Alpha_arb(g: &mut Gen) -> Alpha {
    match g.pick(8) {
        0 => Alpha::alpha0,
        1 => Alpha::alpha04,
        2 => Alpha::alpha05,
        3 => Alpha::alpha06,
        4 => Alpha::alpha07,
        5 => Alpha::alpha08,
        6 => Alpha::alpha09,
        _ => Alpha::alpha1,
    }
}

// ---------------------------------------------------------------- XOverhead
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub enum XOverhead {
    xOh6,
    xOh12,
    xOh18,
}

pub open spec fn XOverhead_to(v: u64) -> XOverhead {
    if v == 0 { XOverhead::xOh6 } else {
    if v == 1 { XOverhead::xOh12 } else {
    XOverhead::xOh18
    }
    }
}

pub open spec fn XOverhead_from(e: XOverhead) -> u64 {
    match e {
        XOverhead::xOh6 => 0,
        XOverhead::xOh12 => 1,
        XOverhead::xOh18 => 2,
    }
}

pub open spec fn XOverhead_ok() -> spec_fn(u64) -> bool { |v: u64| v <= 2 }
pub open spec fn XOverhead_to_f() -> spec_fn(u64) -> XOverhead { |v: u64| XOverhead_to(v) }
pub open spec fn XOverhead_from_f() -> spec_fn(XOverhead) -> u64 { |e: XOverhead| XOverhead_from(e) }
pub open spec fn XOverhead_base_wf() -> Wf<u64> { restrict_wf(uint_wf(2), XOverhead_ok()) }
pub open spec fn XOverhead_base_dec() -> Dec<u64> { restrict_dec(uint_dec(2), XOverhead_ok()) }
pub open spec fn XOverhead_wf() -> Wf<XOverhead> { map_wf(XOverhead_base_wf(), XOverhead_to_f(), XOverhead_from_f()) }
pub open spec fn XOverhead_enc() -> Enc<XOverhead> { map_enc(uint_enc(2), XOverhead_from_f()) }
pub open spec fn XOverhead_dec() -> Dec<XOverhead> { map_dec(XOverhead_base_dec(), XOverhead_to_f()) }

pub proof fn XOverhead_is_format()
    ensures is_format(XOverhead_wf(), XOverhead_enc(), XOverhead_dec()),
{
    lemma_uint_format(2);
    lemma_restrict_format(uint_wf(2), uint_enc(2), uint_dec(2), XOverhead_ok());
    assert forall|v: u64| XOverhead_base_wf()(v) implies
        #[trigger] XOverhead_from_f()(XOverhead_to_f()(v)) == v by { }
    lemma_map_format(XOverhead_base_wf(), uint_enc(2), XOverhead_base_dec(),
                     XOverhead_to_f(), XOverhead_from_f());
}

#[inline]
pub fn XOverhead_of_u64(v: u64) -> (e: XOverhead)
    requires v <= 2,
    ensures e == XOverhead_to(v),
{
    if v == 0 { XOverhead::xOh6 } else {
    if v == 1 { XOverhead::xOh12 } else {
    XOverhead::xOh18
    }
    }
}

#[inline]
pub fn XOverhead_as_u64(e: &XOverhead) -> (v: u64)
    ensures v == XOverhead_from(*e),
{
    match e {
        XOverhead::xOh6 => 0,
        XOverhead::xOh12 => 1,
        XOverhead::xOh18 => 2,
    }
}

#[inline]
pub fn XOverhead_decode(r: &mut BitReader) -> (res: Option<(XOverhead, Flg)>)
    requires old(r).wf(),
    ensures
        final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => XOverhead_dec()(old(r).rem())
                == Some::<(XOverhead, nat, Flg)>((v,
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => XOverhead_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    match r.read_uint(2) {
        Some(v) => if v <= 2 {
            proof {
                lemma_restrict_dec_some(uint_dec(2), XOverhead_ok(), start, v, 2, Flg::SameVer);
                lemma_map_dec_some(XOverhead_base_dec(), XOverhead_to_f(), start, v, 2, Flg::SameVer);
            }
            Some((XOverhead_of_u64(v), Flg::SameVer))
        } else {
            proof {
                lemma_restrict_dec_none(uint_dec(2), XOverhead_ok(), start);
                lemma_map_dec_none(XOverhead_base_dec(), XOverhead_to_f(), start);
            }
            { r.fail("ENUMERATED index (0..2)"); None }
        },
        None => {
            proof {
                lemma_restrict_dec_none(uint_dec(2), XOverhead_ok(), start);
                lemma_map_dec_none(XOverhead_base_dec(), XOverhead_to_f(), start);
            }
            { r.fail("ENUMERATED index (0..2)"); None }
        }
    }
}

#[inline]
pub fn XOverhead_encode(w: &mut BitWriter, e: &XOverhead) -> (ok: bool)
    requires old(w).wf(),
    ensures
        final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + XOverhead_enc()(*e),
{
    let v = XOverhead_as_u64(e);
    proof { assert(uint_wf(2 as nat)(v)) by { reveal_with_fuel(p2, 4); } }
    w.write_uint(2, v)
}

#[verifier::external]
#[inline]
pub fn XOverhead_jer(v: &XOverhead, o: &mut String) {
    match v {
        XOverhead::xOh6 => jer_ident("xOh6", o),
        XOverhead::xOh12 => jer_ident("xOh12", o),
        XOverhead::xOh18 => jer_ident("xOh18", o),
    }
}

#[verifier::external]
#[inline]
pub fn XOverhead_arb(g: &mut Gen) -> XOverhead {
    match g.pick(3) {
        0 => XOverhead::xOh6,
        1 => XOverhead::xOh12,
        _ => XOverhead::xOh18,
    }
}

// ---------------------------------------------------------------- PDSCH-ServingCellConfig
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub struct PDSCH_ServingCellConfig {
    pub nrofHARQ_ProcessesForPDSCH: i64,
    pub pucch_Cell: i64,
    pub xOverhead: XOverhead,
    pub codeBlockGroupTransmission: bool,
    pub alpha: Alpha,
}

pub open spec fn PDSCH_ServingCellConfig_view(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig { m }

pub type PDSCH_ServingCellConfig_T3 = (bool, Alpha);
pub type PDSCH_ServingCellConfig_ET3 = (bool, Alpha);
pub type PDSCH_ServingCellConfig_T2 = (XOverhead, PDSCH_ServingCellConfig_T3);
pub type PDSCH_ServingCellConfig_ET2 = (XOverhead, PDSCH_ServingCellConfig_ET3);
pub type PDSCH_ServingCellConfig_T1 = (i64, i64);
pub type PDSCH_ServingCellConfig_ET1 = (i64, i64);
pub type PDSCH_ServingCellConfig_T0 = (PDSCH_ServingCellConfig_T1, PDSCH_ServingCellConfig_T2);
pub type PDSCH_ServingCellConfig_ET0 = (PDSCH_ServingCellConfig_ET1, PDSCH_ServingCellConfig_ET2);
pub open spec fn PDSCH_ServingCellConfig_view_t3(v: PDSCH_ServingCellConfig_ET3) -> PDSCH_ServingCellConfig_T3 { (v.0, v.1) }
pub open spec fn PDSCH_ServingCellConfig_view_t2(v: PDSCH_ServingCellConfig_ET2) -> PDSCH_ServingCellConfig_T2 { (v.0, PDSCH_ServingCellConfig_view_t3(v.1)) }
pub open spec fn PDSCH_ServingCellConfig_view_t1(v: PDSCH_ServingCellConfig_ET1) -> PDSCH_ServingCellConfig_T1 { (v.0, v.1) }
pub open spec fn PDSCH_ServingCellConfig_view_t0(v: PDSCH_ServingCellConfig_ET0) -> PDSCH_ServingCellConfig_T0 { (PDSCH_ServingCellConfig_view_t1(v.0), PDSCH_ServingCellConfig_view_t2(v.1)) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_tup_t3(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T3 { (m.codeBlockGroupTransmission, m.alpha) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_tup_t2(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T2 { (m.xOverhead, PDSCH_ServingCellConfig_tup_t3(m)) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_tup_t1(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T1 { (m.nrofHARQ_ProcessesForPDSCH, m.pucch_Cell) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_tup_t0(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T0 { (PDSCH_ServingCellConfig_tup_t1(m), PDSCH_ServingCellConfig_tup_t2(m)) }

pub open spec fn PDSCH_ServingCellConfig_to(t: PDSCH_ServingCellConfig_T0) -> PDSCH_ServingCellConfig {
    PDSCH_ServingCellConfig {
        nrofHARQ_ProcessesForPDSCH: t.0.0,
        pucch_Cell: t.0.1,
        xOverhead: t.1.0,
        codeBlockGroupTransmission: t.1.1.0,
        alpha: t.1.1.1,
    }
}

pub open spec fn PDSCH_ServingCellConfig_body(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T0 { ((m.nrofHARQ_ProcessesForPDSCH, m.pucch_Cell), (m.xOverhead, (m.codeBlockGroupTransmission, m.alpha))) }
pub open spec fn PDSCH_ServingCellConfig_from(m: PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T0 { PDSCH_ServingCellConfig_body(m) }
pub open spec fn PDSCH_ServingCellConfig_to_f() -> spec_fn(PDSCH_ServingCellConfig_T0) -> PDSCH_ServingCellConfig { |t: PDSCH_ServingCellConfig_T0| PDSCH_ServingCellConfig_to(t) }
pub open spec fn PDSCH_ServingCellConfig_from_f() -> spec_fn(PDSCH_ServingCellConfig) -> PDSCH_ServingCellConfig_T0 { |m: PDSCH_ServingCellConfig| PDSCH_ServingCellConfig_from(m) }

pub proof fn PDSCH_ServingCellConfig_tup0(m: PDSCH_ServingCellConfig)
    ensures PDSCH_ServingCellConfig_tup_t0(m) == PDSCH_ServingCellConfig_body(m),
{
    reveal(PDSCH_ServingCellConfig_tup_t0);
    reveal(PDSCH_ServingCellConfig_tup_t1);
    reveal(PDSCH_ServingCellConfig_tup_t2);
    reveal(PDSCH_ServingCellConfig_tup_t3);
}

#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_wf_t3() -> Wf<PDSCH_ServingCellConfig_T3> { pair_wf(bool_wf(), Alpha_wf()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_enc_t3() -> Enc<PDSCH_ServingCellConfig_T3> { pair_enc(bool_enc(), Alpha_enc()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_dec_t3() -> Dec<PDSCH_ServingCellConfig_T3> { pair_dec(bool_dec(), Alpha_dec()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_wf_t2() -> Wf<PDSCH_ServingCellConfig_T2> { pair_wf(XOverhead_wf(), PDSCH_ServingCellConfig_wf_t3()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_enc_t2() -> Enc<PDSCH_ServingCellConfig_T2> { pair_enc(XOverhead_enc(), PDSCH_ServingCellConfig_enc_t3()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_dec_t2() -> Dec<PDSCH_ServingCellConfig_T2> { pair_dec(XOverhead_dec(), PDSCH_ServingCellConfig_dec_t3()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_wf_t1() -> Wf<PDSCH_ServingCellConfig_T1> { pair_wf(int_range_wf(1, 16, 4), int_range_wf(0, 31, 5)) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_enc_t1() -> Enc<PDSCH_ServingCellConfig_T1> { pair_enc(int_range_enc(1, 16, 4), int_range_enc(0, 31, 5)) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_dec_t1() -> Dec<PDSCH_ServingCellConfig_T1> { pair_dec(int_range_dec(1, 16, 4), int_range_dec(0, 31, 5)) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_wf_t0() -> Wf<PDSCH_ServingCellConfig_T0> { pair_wf(PDSCH_ServingCellConfig_wf_t1(), PDSCH_ServingCellConfig_wf_t2()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_enc_t0() -> Enc<PDSCH_ServingCellConfig_T0> { pair_enc(PDSCH_ServingCellConfig_enc_t1(), PDSCH_ServingCellConfig_enc_t2()) }
#[verifier::opaque]
pub open spec fn PDSCH_ServingCellConfig_dec_t0() -> Dec<PDSCH_ServingCellConfig_T0> { pair_dec(PDSCH_ServingCellConfig_dec_t1(), PDSCH_ServingCellConfig_dec_t2()) }

pub open spec fn PDSCH_ServingCellConfig_full_wf() -> Wf<PDSCH_ServingCellConfig_T0> { PDSCH_ServingCellConfig_wf_t0() }
pub open spec fn PDSCH_ServingCellConfig_full_enc() -> Enc<PDSCH_ServingCellConfig_T0> { PDSCH_ServingCellConfig_enc_t0() }
pub open spec fn PDSCH_ServingCellConfig_full_dec() -> Dec<PDSCH_ServingCellConfig_T0> { PDSCH_ServingCellConfig_dec_t0() }

pub open spec fn PDSCH_ServingCellConfig_wf() -> Wf<PDSCH_ServingCellConfig> { map_wf(PDSCH_ServingCellConfig_full_wf(), PDSCH_ServingCellConfig_to_f(), PDSCH_ServingCellConfig_from_f()) }
pub open spec fn PDSCH_ServingCellConfig_enc() -> Enc<PDSCH_ServingCellConfig> { map_enc(PDSCH_ServingCellConfig_full_enc(), PDSCH_ServingCellConfig_from_f()) }
pub open spec fn PDSCH_ServingCellConfig_dec() -> Dec<PDSCH_ServingCellConfig> { map_dec(PDSCH_ServingCellConfig_full_dec(), PDSCH_ServingCellConfig_to_f()) }

pub proof fn PDSCH_ServingCellConfig_body_is_format_t3()
    ensures is_format(PDSCH_ServingCellConfig_wf_t3(), PDSCH_ServingCellConfig_enc_t3(), PDSCH_ServingCellConfig_dec_t3()),
{
    reveal(PDSCH_ServingCellConfig_wf_t3); reveal(PDSCH_ServingCellConfig_enc_t3); reveal(PDSCH_ServingCellConfig_dec_t3);
    lemma_bool_format();
    Alpha_is_format();
    lemma_pair_format(bool_wf(), bool_enc(), bool_dec(), Alpha_wf(), Alpha_enc(), Alpha_dec());
}

pub proof fn PDSCH_ServingCellConfig_body_is_format_t2()
    ensures is_format(PDSCH_ServingCellConfig_wf_t2(), PDSCH_ServingCellConfig_enc_t2(), PDSCH_ServingCellConfig_dec_t2()),
{
    reveal(PDSCH_ServingCellConfig_wf_t2); reveal(PDSCH_ServingCellConfig_enc_t2); reveal(PDSCH_ServingCellConfig_dec_t2);
    XOverhead_is_format();
    PDSCH_ServingCellConfig_body_is_format_t3();
    lemma_pair_format(XOverhead_wf(), XOverhead_enc(), XOverhead_dec(), PDSCH_ServingCellConfig_wf_t3(), PDSCH_ServingCellConfig_enc_t3(), PDSCH_ServingCellConfig_dec_t3());
}

pub proof fn PDSCH_ServingCellConfig_body_is_format_t1()
    ensures is_format(PDSCH_ServingCellConfig_wf_t1(), PDSCH_ServingCellConfig_enc_t1(), PDSCH_ServingCellConfig_dec_t1()),
{
    reveal(PDSCH_ServingCellConfig_wf_t1); reveal(PDSCH_ServingCellConfig_enc_t1); reveal(PDSCH_ServingCellConfig_dec_t1);
    assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } lemma_int_range_format(1, 16, 4);
    assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } lemma_int_range_format(0, 31, 5);
    lemma_pair_format(int_range_wf(1, 16, 4), int_range_enc(1, 16, 4), int_range_dec(1, 16, 4), int_range_wf(0, 31, 5), int_range_enc(0, 31, 5), int_range_dec(0, 31, 5));
}

pub proof fn PDSCH_ServingCellConfig_body_is_format_t0()
    ensures is_format(PDSCH_ServingCellConfig_wf_t0(), PDSCH_ServingCellConfig_enc_t0(), PDSCH_ServingCellConfig_dec_t0()),
{
    reveal(PDSCH_ServingCellConfig_wf_t0); reveal(PDSCH_ServingCellConfig_enc_t0); reveal(PDSCH_ServingCellConfig_dec_t0);
    PDSCH_ServingCellConfig_body_is_format_t1();
    PDSCH_ServingCellConfig_body_is_format_t2();
    lemma_pair_format(PDSCH_ServingCellConfig_wf_t1(), PDSCH_ServingCellConfig_enc_t1(), PDSCH_ServingCellConfig_dec_t1(), PDSCH_ServingCellConfig_wf_t2(), PDSCH_ServingCellConfig_enc_t2(), PDSCH_ServingCellConfig_dec_t2());
}

pub proof fn PDSCH_ServingCellConfig_body_is_format()
    ensures is_format(PDSCH_ServingCellConfig_wf_t0(), PDSCH_ServingCellConfig_enc_t0(), PDSCH_ServingCellConfig_dec_t0()),
{
    PDSCH_ServingCellConfig_body_is_format_t0();
}

pub proof fn PDSCH_ServingCellConfig_is_format()
    ensures is_format(PDSCH_ServingCellConfig_wf(), PDSCH_ServingCellConfig_enc(), PDSCH_ServingCellConfig_dec()),
{
    reveal(PDSCH_ServingCellConfig_wf_t0);
    reveal(PDSCH_ServingCellConfig_wf_t1);
    reveal(PDSCH_ServingCellConfig_wf_t2);
    reveal(PDSCH_ServingCellConfig_wf_t3);
    PDSCH_ServingCellConfig_body_is_format();
    assert forall|t: PDSCH_ServingCellConfig_T0| PDSCH_ServingCellConfig_full_wf()(t) implies
        #[trigger] PDSCH_ServingCellConfig_from_f()(PDSCH_ServingCellConfig_to_f()(t)) == t by { }
    lemma_map_format(PDSCH_ServingCellConfig_full_wf(), PDSCH_ServingCellConfig_full_enc(), PDSCH_ServingCellConfig_full_dec(),
                     PDSCH_ServingCellConfig_to_f(), PDSCH_ServingCellConfig_from_f());
}

pub proof fn PDSCH_ServingCellConfig_field_bounds(v: PDSCH_ServingCellConfig)
    requires PDSCH_ServingCellConfig_wf()(v),
    ensures PDSCH_ServingCellConfig_full_wf()(PDSCH_ServingCellConfig_from(v)),
{
    assert(PDSCH_ServingCellConfig_from_f()(PDSCH_ServingCellConfig_to_f()(PDSCH_ServingCellConfig_from(v))) == PDSCH_ServingCellConfig_from(v));
}

#[inline]
pub fn PDSCH_ServingCellConfig_dec_t3_run(r: &mut BitReader) -> (res: Option<(PDSCH_ServingCellConfig_ET3, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => PDSCH_ServingCellConfig_dec_t3()(old(r).rem())
                == Some::<(PDSCH_ServingCellConfig_T3, nat, Flg)>((PDSCH_ServingCellConfig_view_t3(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => PDSCH_ServingCellConfig_dec_t3()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_dec_t3); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match { let o_ = r.read_bool(); r.same(o_, "BOOLEAN") } {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(bool_dec(), Alpha_dec(), start); }
            r.fail_in("codeBlockGroupTransmission"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match Alpha_decode(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(bool_dec(), Alpha_dec(), start, head, kh, fh); }
            r.fail_in("alpha"); return None;
        }
    };
    proof { lemma_pair_dec_some(bool_dec(), Alpha_dec(), start, head, kh, fh, tail,
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn PDSCH_ServingCellConfig_dec_t2_run(r: &mut BitReader) -> (res: Option<(PDSCH_ServingCellConfig_ET2, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => PDSCH_ServingCellConfig_dec_t2()(old(r).rem())
                == Some::<(PDSCH_ServingCellConfig_T2, nat, Flg)>((PDSCH_ServingCellConfig_view_t2(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => PDSCH_ServingCellConfig_dec_t2()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_dec_t2); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match XOverhead_decode(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(XOverhead_dec(), PDSCH_ServingCellConfig_dec_t3(), start); }
            r.fail_in("xOverhead"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match PDSCH_ServingCellConfig_dec_t3_run(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(XOverhead_dec(), PDSCH_ServingCellConfig_dec_t3(), start, head, kh, fh); }
             return None;
        }
    };
    proof { lemma_pair_dec_some(XOverhead_dec(), PDSCH_ServingCellConfig_dec_t3(), start, head, kh, fh, PDSCH_ServingCellConfig_view_t3(tail),
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn PDSCH_ServingCellConfig_dec_t1_run(r: &mut BitReader) -> (res: Option<(PDSCH_ServingCellConfig_ET1, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => PDSCH_ServingCellConfig_dec_t1()(old(r).rem())
                == Some::<(PDSCH_ServingCellConfig_T1, nat, Flg)>((PDSCH_ServingCellConfig_view_t1(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => PDSCH_ServingCellConfig_dec_t1()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_dec_t1); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match { let o_ = r.read_int_range(1, 16, 4); r.same(o_, "INTEGER (1..16)") } {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(int_range_dec(1, 16, 4), int_range_dec(0, 31, 5), start); }
            r.fail_in("nrofHARQ-ProcessesForPDSCH"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match { let o_ = r.read_int_range(0, 31, 5); r.same(o_, "INTEGER (0..31)") } {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(int_range_dec(1, 16, 4), int_range_dec(0, 31, 5), start, head, kh, fh); }
            r.fail_in("pucch-Cell"); return None;
        }
    };
    proof { lemma_pair_dec_some(int_range_dec(1, 16, 4), int_range_dec(0, 31, 5), start, head, kh, fh, tail,
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn PDSCH_ServingCellConfig_dec_t0_run(r: &mut BitReader) -> (res: Option<(PDSCH_ServingCellConfig_ET0, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => PDSCH_ServingCellConfig_dec_t0()(old(r).rem())
                == Some::<(PDSCH_ServingCellConfig_T0, nat, Flg)>((PDSCH_ServingCellConfig_view_t0(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => PDSCH_ServingCellConfig_dec_t0()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_dec_t0); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match PDSCH_ServingCellConfig_dec_t1_run(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(PDSCH_ServingCellConfig_dec_t1(), PDSCH_ServingCellConfig_dec_t2(), start); }
             return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match PDSCH_ServingCellConfig_dec_t2_run(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(PDSCH_ServingCellConfig_dec_t1(), PDSCH_ServingCellConfig_dec_t2(), start, PDSCH_ServingCellConfig_view_t1(head), kh, fh); }
             return None;
        }
    };
    proof { lemma_pair_dec_some(PDSCH_ServingCellConfig_dec_t1(), PDSCH_ServingCellConfig_dec_t2(), start, PDSCH_ServingCellConfig_view_t1(head), kh, fh, PDSCH_ServingCellConfig_view_t2(tail),
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn PDSCH_ServingCellConfig_decode(r: &mut BitReader) -> (res: Option<(PDSCH_ServingCellConfig, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => PDSCH_ServingCellConfig_dec()(old(r).rem())
                == Some::<(PDSCH_ServingCellConfig, nat, Flg)>((PDSCH_ServingCellConfig_view(v),
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => PDSCH_ServingCellConfig_dec()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (body, fb) = match PDSCH_ServingCellConfig_dec_t0_run(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_map_dec_none(PDSCH_ServingCellConfig_full_dec(), PDSCH_ServingCellConfig_to_f(), start); }
             return None;
        }
    };
    proof { lemma_map_dec_some(PDSCH_ServingCellConfig_full_dec(), PDSCH_ServingCellConfig_to_f(), start, PDSCH_ServingCellConfig_view_t0(body),
                               (r.pos - p0) as nat, fb); }
    Some((PDSCH_ServingCellConfig { nrofHARQ_ProcessesForPDSCH: body.0.0, pucch_Cell: body.0.1, xOverhead: body.1.0, codeBlockGroupTransmission: body.1.1.0, alpha: body.1.1.1, }, fb))
}

#[inline]
pub fn PDSCH_ServingCellConfig_enc_t3_run(w: &mut BitWriter, m: &PDSCH_ServingCellConfig) -> (ok: bool)
    requires old(w).wf(), PDSCH_ServingCellConfig_wf_t3()(PDSCH_ServingCellConfig_tup_t3(PDSCH_ServingCellConfig_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + PDSCH_ServingCellConfig_enc_t3()(PDSCH_ServingCellConfig_tup_t3(PDSCH_ServingCellConfig_view(*m))),
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_tup_t3); reveal(PDSCH_ServingCellConfig_wf_t3); reveal(PDSCH_ServingCellConfig_enc_t3); }
    if !w.write_bool(m.codeBlockGroupTransmission) { return false; }
    if !Alpha_encode(w, &m.alpha) { return false; }
    true
}

#[inline]
pub fn PDSCH_ServingCellConfig_enc_t2_run(w: &mut BitWriter, m: &PDSCH_ServingCellConfig) -> (ok: bool)
    requires old(w).wf(), PDSCH_ServingCellConfig_wf_t2()(PDSCH_ServingCellConfig_tup_t2(PDSCH_ServingCellConfig_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + PDSCH_ServingCellConfig_enc_t2()(PDSCH_ServingCellConfig_tup_t2(PDSCH_ServingCellConfig_view(*m))),
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_tup_t2); reveal(PDSCH_ServingCellConfig_wf_t2); reveal(PDSCH_ServingCellConfig_enc_t2); }
    if !XOverhead_encode(w, &m.xOverhead) { return false; }
    if !PDSCH_ServingCellConfig_enc_t3_run(w, m) { return false; }
    true
}

#[inline]
pub fn PDSCH_ServingCellConfig_enc_t1_run(w: &mut BitWriter, m: &PDSCH_ServingCellConfig) -> (ok: bool)
    requires old(w).wf(), PDSCH_ServingCellConfig_wf_t1()(PDSCH_ServingCellConfig_tup_t1(PDSCH_ServingCellConfig_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + PDSCH_ServingCellConfig_enc_t1()(PDSCH_ServingCellConfig_tup_t1(PDSCH_ServingCellConfig_view(*m))),
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_tup_t1); reveal(PDSCH_ServingCellConfig_wf_t1); reveal(PDSCH_ServingCellConfig_enc_t1); }
    if !w.write_int_range(1, 16, 4, m.nrofHARQ_ProcessesForPDSCH) { return false; }
    if !w.write_int_range(0, 31, 5, m.pucch_Cell) { return false; }
    true
}

#[inline]
pub fn PDSCH_ServingCellConfig_enc_t0_run(w: &mut BitWriter, m: &PDSCH_ServingCellConfig) -> (ok: bool)
    requires old(w).wf(), PDSCH_ServingCellConfig_wf_t0()(PDSCH_ServingCellConfig_tup_t0(PDSCH_ServingCellConfig_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + PDSCH_ServingCellConfig_enc_t0()(PDSCH_ServingCellConfig_tup_t0(PDSCH_ServingCellConfig_view(*m))),
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(PDSCH_ServingCellConfig_tup_t0); reveal(PDSCH_ServingCellConfig_wf_t0); reveal(PDSCH_ServingCellConfig_enc_t0); }
    if !PDSCH_ServingCellConfig_enc_t1_run(w, m) { return false; }
    if !PDSCH_ServingCellConfig_enc_t2_run(w, m) { return false; }
    true
}

pub proof fn PDSCH_ServingCellConfig_enc_pre(v: PDSCH_ServingCellConfig)
    requires PDSCH_ServingCellConfig_wf()(v),
    ensures PDSCH_ServingCellConfig_wf_t0()(PDSCH_ServingCellConfig_tup_t0(v)),
        PDSCH_ServingCellConfig_enc()(v) =~= PDSCH_ServingCellConfig_enc_t0()(PDSCH_ServingCellConfig_tup_t0(v)),
{
    PDSCH_ServingCellConfig_field_bounds(v);
    PDSCH_ServingCellConfig_tup0(v);
    assert(PDSCH_ServingCellConfig_enc()(v) =~= PDSCH_ServingCellConfig_full_enc()(PDSCH_ServingCellConfig_from(v)));
}

#[inline]
pub fn PDSCH_ServingCellConfig_encode(w: &mut BitWriter, m: &PDSCH_ServingCellConfig) -> (ok: bool)
    requires old(w).wf(), PDSCH_ServingCellConfig_wf()(PDSCH_ServingCellConfig_view(*m)),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + PDSCH_ServingCellConfig_enc()(PDSCH_ServingCellConfig_view(*m)),
{
    proof { assert(p2(4) == 16) by { reveal_with_fuel(p2, 6); } }
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { PDSCH_ServingCellConfig_enc_pre(PDSCH_ServingCellConfig_view(*m)); }
    let ok = PDSCH_ServingCellConfig_enc_t0_run(w, m);
    ok
}

#[verifier::external]
#[inline]
pub fn PDSCH_ServingCellConfig_jer_members(v: &PDSCH_ServingCellConfig, o: &mut String, first: &mut bool) {
    { jer_member("nrofHARQ-ProcessesForPDSCH", first, o); jer_int(*&v.nrofHARQ_ProcessesForPDSCH, o); }
    { jer_member("pucch-Cell", first, o); jer_int(*&v.pucch_Cell, o); }
    { jer_member("xOverhead", first, o); XOverhead_jer(&v.xOverhead, o); }
    { jer_member("codeBlockGroupTransmission", first, o); jer_bool(*&v.codeBlockGroupTransmission, o); }
    { jer_member("alpha", first, o); Alpha_jer(&v.alpha, o); }
}

#[verifier::external]
#[inline]
pub fn PDSCH_ServingCellConfig_jer(v: &PDSCH_ServingCellConfig, o: &mut String) {
    o.push('{');
    let mut first = true;
    PDSCH_ServingCellConfig_jer_members(v, o, &mut first);
    o.push('}');
}

#[verifier::external]
#[inline]
pub fn PDSCH_ServingCellConfig_arb(g: &mut Gen) -> PDSCH_ServingCellConfig {
    PDSCH_ServingCellConfig {
        nrofHARQ_ProcessesForPDSCH: g.range(1, 16),
        pucch_Cell: g.range(0, 31),
        xOverhead: XOverhead_arb(g),
        codeBlockGroupTransmission: g.bool(),
        alpha: Alpha_arb(g),
    }
}

// ---------------------------------------------------------------- Pair
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub struct Pair {
    pub first: bool,
    pub second: i64,
}

pub open spec fn Pair_view(m: Pair) -> Pair { m }

pub type Pair_T0 = (bool, i64);
pub type Pair_ET0 = (bool, i64);
pub open spec fn Pair_view_t0(v: Pair_ET0) -> Pair_T0 { (v.0, v.1) }
#[verifier::opaque]
pub open spec fn Pair_tup_t0(m: Pair) -> Pair_T0 { (m.first, m.second) }

pub open spec fn Pair_to(t: Pair_T0) -> Pair {
    Pair {
        first: t.0,
        second: t.1,
    }
}

pub open spec fn Pair_body(m: Pair) -> Pair_T0 { (m.first, m.second) }
pub open spec fn Pair_from(m: Pair) -> Pair_T0 { Pair_body(m) }
pub open spec fn Pair_to_f() -> spec_fn(Pair_T0) -> Pair { |t: Pair_T0| Pair_to(t) }
pub open spec fn Pair_from_f() -> spec_fn(Pair) -> Pair_T0 { |m: Pair| Pair_from(m) }

pub proof fn Pair_tup0(m: Pair)
    ensures Pair_tup_t0(m) == Pair_body(m),
{
    reveal(Pair_tup_t0);
}

#[verifier::opaque]
pub open spec fn Pair_wf_t0() -> Wf<Pair_T0> { pair_wf(bool_wf(), int_range_wf(0, 31, 5)) }
#[verifier::opaque]
pub open spec fn Pair_enc_t0() -> Enc<Pair_T0> { pair_enc(bool_enc(), int_range_enc(0, 31, 5)) }
#[verifier::opaque]
pub open spec fn Pair_dec_t0() -> Dec<Pair_T0> { pair_dec(bool_dec(), int_range_dec(0, 31, 5)) }

pub open spec fn Pair_full_wf() -> Wf<Pair_T0> { Pair_wf_t0() }
pub open spec fn Pair_full_enc() -> Enc<Pair_T0> { Pair_enc_t0() }
pub open spec fn Pair_full_dec() -> Dec<Pair_T0> { Pair_dec_t0() }

pub open spec fn Pair_wf() -> Wf<Pair> { map_wf(Pair_full_wf(), Pair_to_f(), Pair_from_f()) }
pub open spec fn Pair_enc() -> Enc<Pair> { map_enc(Pair_full_enc(), Pair_from_f()) }
pub open spec fn Pair_dec() -> Dec<Pair> { map_dec(Pair_full_dec(), Pair_to_f()) }

pub proof fn Pair_body_is_format_t0()
    ensures is_format(Pair_wf_t0(), Pair_enc_t0(), Pair_dec_t0()),
{
    reveal(Pair_wf_t0); reveal(Pair_enc_t0); reveal(Pair_dec_t0);
    lemma_bool_format();
    assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } lemma_int_range_format(0, 31, 5);
    lemma_pair_format(bool_wf(), bool_enc(), bool_dec(), int_range_wf(0, 31, 5), int_range_enc(0, 31, 5), int_range_dec(0, 31, 5));
}

pub proof fn Pair_body_is_format()
    ensures is_format(Pair_wf_t0(), Pair_enc_t0(), Pair_dec_t0()),
{
    Pair_body_is_format_t0();
}

pub proof fn Pair_is_format()
    ensures is_format(Pair_wf(), Pair_enc(), Pair_dec()),
{
    reveal(Pair_wf_t0);
    Pair_body_is_format();
    assert forall|t: Pair_T0| Pair_full_wf()(t) implies
        #[trigger] Pair_from_f()(Pair_to_f()(t)) == t by { }
    lemma_map_format(Pair_full_wf(), Pair_full_enc(), Pair_full_dec(),
                     Pair_to_f(), Pair_from_f());
}

pub proof fn Pair_field_bounds(v: Pair)
    requires Pair_wf()(v),
    ensures Pair_full_wf()(Pair_from(v)),
{
    assert(Pair_from_f()(Pair_to_f()(Pair_from(v))) == Pair_from(v));
}

#[inline]
pub fn Pair_dec_t0_run(r: &mut BitReader) -> (res: Option<(Pair_ET0, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Pair_dec_t0()(old(r).rem())
                == Some::<(Pair_T0, nat, Flg)>((Pair_view_t0(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => Pair_dec_t0()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(Pair_dec_t0); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match { let o_ = r.read_bool(); r.same(o_, "BOOLEAN") } {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(bool_dec(), int_range_dec(0, 31, 5), start); }
            r.fail_in("first"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match { let o_ = r.read_int_range(0, 31, 5); r.same(o_, "INTEGER (0..31)") } {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(bool_dec(), int_range_dec(0, 31, 5), start, head, kh, fh); }
            r.fail_in("second"); return None;
        }
    };
    proof { lemma_pair_dec_some(bool_dec(), int_range_dec(0, 31, 5), start, head, kh, fh, tail,
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn Pair_decode(r: &mut BitReader) -> (res: Option<(Pair, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Pair_dec()(old(r).rem())
                == Some::<(Pair, nat, Flg)>((Pair_view(v),
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => Pair_dec()(old(r).rem()).is_none(),
        },
{
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (body, fb) = match Pair_dec_t0_run(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_map_dec_none(Pair_full_dec(), Pair_to_f(), start); }
             return None;
        }
    };
    proof { lemma_map_dec_some(Pair_full_dec(), Pair_to_f(), start, Pair_view_t0(body),
                               (r.pos - p0) as nat, fb); }
    Some((Pair { first: body.0, second: body.1, }, fb))
}

#[inline]
pub fn Pair_enc_t0_run(w: &mut BitWriter, m: &Pair) -> (ok: bool)
    requires old(w).wf(), Pair_wf_t0()(Pair_tup_t0(Pair_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Pair_enc_t0()(Pair_tup_t0(Pair_view(*m))),
{
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { reveal(Pair_tup_t0); reveal(Pair_wf_t0); reveal(Pair_enc_t0); }
    if !w.write_bool(m.first) { return false; }
    if !w.write_int_range(0, 31, 5, m.second) { return false; }
    true
}

pub proof fn Pair_enc_pre(v: Pair)
    requires Pair_wf()(v),
    ensures Pair_wf_t0()(Pair_tup_t0(v)),
        Pair_enc()(v) =~= Pair_enc_t0()(Pair_tup_t0(v)),
{
    Pair_field_bounds(v);
    Pair_tup0(v);
    assert(Pair_enc()(v) =~= Pair_full_enc()(Pair_from(v)));
}

#[inline]
pub fn Pair_encode(w: &mut BitWriter, m: &Pair) -> (ok: bool)
    requires old(w).wf(), Pair_wf()(Pair_view(*m)),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Pair_enc()(Pair_view(*m)),
{
    proof { assert(p2(5) == 32) by { reveal_with_fuel(p2, 7); } }
    proof { Pair_enc_pre(Pair_view(*m)); }
    let ok = Pair_enc_t0_run(w, m);
    ok
}

#[verifier::external]
#[inline]
pub fn Pair_jer_members(v: &Pair, o: &mut String, first: &mut bool) {
    { jer_member("first", first, o); jer_bool(*&v.first, o); }
    { jer_member("second", first, o); jer_int(*&v.second, o); }
}

#[verifier::external]
#[inline]
pub fn Pair_jer(v: &Pair, o: &mut String) {
    o.push('{');
    let mut first = true;
    Pair_jer_members(v, o, &mut first);
    o.push('}');
}

#[verifier::external]
#[inline]
pub fn Pair_arb(g: &mut Gen) -> Pair {
    Pair {
        first: g.bool(),
        second: g.range(0, 31),
    }
}

// ---------------------------------------------------------------- Unsupported-1
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub struct Unsupported_1 {
    pub a: bool,
    pub b: Option<bool>,
}

pub open spec fn Unsupported_1_view(m: Unsupported_1) -> Unsupported_1 { m }

pub type Unsupported_1_T0 = (bool, Option<bool>);
pub type Unsupported_1_ET0 = (bool, Option<bool>);
pub open spec fn Unsupported_1_view_t0(v: Unsupported_1_ET0) -> Unsupported_1_T0 { (v.0, v.1) }
#[verifier::opaque]
pub open spec fn Unsupported_1_tup_t0(m: Unsupported_1) -> Unsupported_1_T0 { (m.a, m.b) }

pub open spec fn Unsupported_1_bm_wf() -> Wf<bool> { bool_wf() }
pub open spec fn Unsupported_1_bm_enc() -> Enc<bool> { bool_enc() }
pub open spec fn Unsupported_1_bm_dec() -> Dec<bool> { bool_dec() }

pub proof fn Unsupported_1_bm_is_format()
    ensures is_format(Unsupported_1_bm_wf(), Unsupported_1_bm_enc(), Unsupported_1_bm_dec()),
{
    lemma_bool_format();
}

pub open spec fn Unsupported_1_to(t: (bool, Unsupported_1_T0)) -> Unsupported_1 {
    Unsupported_1 {
        a: t.1.0,
        b: t.1.1,
    }
}

pub open spec fn Unsupported_1_body(m: Unsupported_1) -> Unsupported_1_T0 { (m.a, m.b) }
#[verifier::opaque]
pub open spec fn Unsupported_1_bm(m: Unsupported_1) -> bool { m.b is Some }
pub open spec fn Unsupported_1_from(m: Unsupported_1) -> (bool, Unsupported_1_T0) { (Unsupported_1_bm(m), Unsupported_1_body(m)) }
pub open spec fn Unsupported_1_to_f() -> spec_fn((bool, Unsupported_1_T0)) -> Unsupported_1 { |t: (bool, Unsupported_1_T0)| Unsupported_1_to(t) }
pub open spec fn Unsupported_1_from_f() -> spec_fn(Unsupported_1) -> (bool, Unsupported_1_T0) { |m: Unsupported_1| Unsupported_1_from(m) }

pub proof fn Unsupported_1_tup0(m: Unsupported_1)
    ensures Unsupported_1_tup_t0(m) == Unsupported_1_body(m),
{
    reveal(Unsupported_1_tup_t0);
}

#[verifier::opaque]
pub open spec fn Unsupported_1_wf_t0(bm: bool) -> Wf<Unsupported_1_T0> { pair_wf(bool_wf(), opt_wf(bm, bool_wf())) }
#[verifier::opaque]
pub open spec fn Unsupported_1_enc_t0(bm: bool) -> Enc<Unsupported_1_T0> { pair_enc(bool_enc(), opt_enc(bm, bool_enc())) }
#[verifier::opaque]
pub open spec fn Unsupported_1_dec_t0(bm: bool) -> Dec<Unsupported_1_T0> { pair_dec(bool_dec(), opt_dec(bm, bool_dec())) }

pub open spec fn Unsupported_1_body_wf() -> spec_fn(bool) -> Wf<Unsupported_1_T0> { |bm: bool| Unsupported_1_wf_t0(bm) }
pub open spec fn Unsupported_1_body_enc() -> spec_fn(bool) -> Enc<Unsupported_1_T0> { |bm: bool| Unsupported_1_enc_t0(bm) }
pub open spec fn Unsupported_1_body_dec() -> spec_fn(bool) -> Dec<Unsupported_1_T0> { |bm: bool| Unsupported_1_dec_t0(bm) }

pub open spec fn Unsupported_1_full_wf() -> Wf<(bool, Unsupported_1_T0)> { dep_wf(Unsupported_1_bm_wf(), Unsupported_1_body_wf()) }
pub open spec fn Unsupported_1_full_enc() -> Enc<(bool, Unsupported_1_T0)> { dep_enc(Unsupported_1_bm_enc(), Unsupported_1_body_enc()) }
pub open spec fn Unsupported_1_full_dec() -> Dec<(bool, Unsupported_1_T0)> { dep_dec(Unsupported_1_bm_dec(), Unsupported_1_body_dec()) }

pub open spec fn Unsupported_1_wf() -> Wf<Unsupported_1> { map_wf(Unsupported_1_full_wf(), Unsupported_1_to_f(), Unsupported_1_from_f()) }
pub open spec fn Unsupported_1_enc() -> Enc<Unsupported_1> { map_enc(Unsupported_1_full_enc(), Unsupported_1_from_f()) }
pub open spec fn Unsupported_1_dec() -> Dec<Unsupported_1> { map_dec(Unsupported_1_full_dec(), Unsupported_1_to_f()) }

pub proof fn Unsupported_1_body_is_format_t0(bm: bool)
    ensures is_format(Unsupported_1_wf_t0(bm), Unsupported_1_enc_t0(bm), Unsupported_1_dec_t0(bm)),
{
    reveal(Unsupported_1_wf_t0); reveal(Unsupported_1_enc_t0); reveal(Unsupported_1_dec_t0);
    lemma_bool_format();
    lemma_bool_format();
    lemma_opt_format(bm, bool_wf(), bool_enc(), bool_dec());
    lemma_pair_format(bool_wf(), bool_enc(), bool_dec(), opt_wf(bm, bool_wf()), opt_enc(bm, bool_enc()), opt_dec(bm, bool_dec()));
}

pub proof fn Unsupported_1_body_is_format(bm: bool)
    ensures is_format(Unsupported_1_wf_t0(bm), Unsupported_1_enc_t0(bm), Unsupported_1_dec_t0(bm)),
{
    Unsupported_1_body_is_format_t0(bm);
}

pub proof fn Unsupported_1_bits_t0(bm: bool, t: Unsupported_1_T0)
    requires Unsupported_1_wf_t0(bm)(t),
    ensures
        (t.1 is Some) == bm,
{
    reveal(Unsupported_1_wf_t0);
    lemma_pair_wf_val(bool_wf(), opt_wf(bm, bool_wf()), t.0, t.1);
    assert(t == (t.0, t.1));
}

pub proof fn Unsupported_1_rt(t: (bool, Unsupported_1_T0))
    requires Unsupported_1_full_wf()(t),
    ensures Unsupported_1_from_f()(Unsupported_1_to_f()(t)) == t,
{
    reveal(Unsupported_1_bm);
    Unsupported_1_bits_t0(t.0, t.1);
}

pub proof fn Unsupported_1_is_format()
    ensures is_format(Unsupported_1_wf(), Unsupported_1_enc(), Unsupported_1_dec()),
{
    Unsupported_1_bm_is_format();
    assert forall|bm: bool| Unsupported_1_bm_wf()(bm) implies
        is_format(#[trigger] Unsupported_1_body_wf()(bm), Unsupported_1_body_enc()(bm), Unsupported_1_body_dec()(bm))
    by { Unsupported_1_body_is_format(bm); }
    lemma_dep_format(Unsupported_1_bm_wf(), Unsupported_1_bm_enc(), Unsupported_1_bm_dec(),
                     Unsupported_1_body_wf(), Unsupported_1_body_enc(), Unsupported_1_body_dec());
    assert forall|t: (bool, Unsupported_1_T0)| Unsupported_1_full_wf()(t) implies
        #[trigger] Unsupported_1_from_f()(Unsupported_1_to_f()(t)) == t by { Unsupported_1_rt(t); }
    lemma_map_format(Unsupported_1_full_wf(), Unsupported_1_full_enc(), Unsupported_1_full_dec(),
                     Unsupported_1_to_f(), Unsupported_1_from_f());
}

pub proof fn Unsupported_1_field_bounds(v: Unsupported_1)
    requires Unsupported_1_wf()(v),
    ensures Unsupported_1_full_wf()(Unsupported_1_from(v)),
{
    assert(Unsupported_1_from_f()(Unsupported_1_to_f()(Unsupported_1_from(v))) == Unsupported_1_from(v));
}

#[inline]
pub fn Unsupported_1_f1_run(r: &mut BitReader, present: bool) -> (res: Option<(Option<bool>, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => opt_dec(present, bool_dec())(old(r).rem())
                == Some::<(Option<bool>, nat, Flg)>((v,
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => opt_dec(present, bool_dec())(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    if present {
        match { let o_ = r.read_bool(); r.same(o_, "BOOLEAN") } {
            Some((v, f)) => {
                proof { lemma_opt_dec_some(bool_enc(), bool_dec(), start, v,
                                           (r.pos - p0) as nat, f); }
                Some((Some(v), f))
            }
            None => {
                proof { lemma_opt_dec_fail(bool_dec(), start); }
                None
            }
        }
    } else {
        proof { lemma_opt_dec_absent(bool_dec(), start); }
        Some((None, Flg::SameVer))
    }
}

#[inline]
pub fn Unsupported_1_dec_t0_run(r: &mut BitReader, bm: bool) -> (res: Option<(Unsupported_1_ET0, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Unsupported_1_dec_t0(bm)(old(r).rem())
                == Some::<(Unsupported_1_T0, nat, Flg)>((Unsupported_1_view_t0(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => Unsupported_1_dec_t0(bm)(old(r).rem()).is_none(),
        },
{
    proof { reveal(Unsupported_1_dec_t0); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match { let o_ = r.read_bool(); r.same(o_, "BOOLEAN") } {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(bool_dec(), opt_dec(bm, bool_dec()), start); }
            r.fail_in("a"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match Unsupported_1_f1_run(r, bm) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(bool_dec(), opt_dec(bm, bool_dec()), start, head, kh, fh); }
            r.fail_in("b"); return None;
        }
    };
    proof { lemma_pair_dec_some(bool_dec(), opt_dec(bm, bool_dec()), start, head, kh, fh, tail,
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn Unsupported_1_decode(r: &mut BitReader) -> (res: Option<(Unsupported_1, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Unsupported_1_dec()(old(r).rem())
                == Some::<(Unsupported_1, nat, Flg)>((Unsupported_1_view(v),
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => Unsupported_1_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let bm = match { let o_ = r.read_bool(); r.got(o_, "preamble") } {
        Some(v) => v,
        None => {
            proof {
                lemma_dep_dec_none_fst(Unsupported_1_bm_dec(), Unsupported_1_body_dec(), start);
                lemma_map_dec_none(Unsupported_1_full_dec(), Unsupported_1_to_f(), start);
            }
            return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kbm = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (body, fb) = match Unsupported_1_dec_t0_run(r, bm) {
        Some(vf) => vf,
        None => {
            proof {
                lemma_dep_dec_none_snd(Unsupported_1_bm_dec(), Unsupported_1_body_dec(), start, bm, kbm,
                                      Flg::SameVer);
                lemma_map_dec_none(Unsupported_1_full_dec(), Unsupported_1_to_f(), start);
            }
             return None;
        }
    };
    proof {
        lemma_dep_dec_some(Unsupported_1_bm_dec(), Unsupported_1_body_dec(), start, bm, kbm, Flg::SameVer,
                           Unsupported_1_view_t0(body), (r.pos - p1) as nat, fb);
        lemma_map_dec_some(Unsupported_1_full_dec(), Unsupported_1_to_f(), start, (bm, Unsupported_1_view_t0(body)),
                           (r.pos - p0) as nat, fb);
    }
    Some((Unsupported_1 { a: body.0, b: body.1, }, fb))
}

#[inline]
pub fn Unsupported_1_enc_t0_run(w: &mut BitWriter, bm: bool, m: &Unsupported_1) -> (ok: bool)
    requires old(w).wf(), Unsupported_1_wf_t0(bm)(Unsupported_1_tup_t0(Unsupported_1_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Unsupported_1_enc_t0(bm)(Unsupported_1_tup_t0(Unsupported_1_view(*m))),
{
    proof { reveal(Unsupported_1_tup_t0); reveal(Unsupported_1_wf_t0); reveal(Unsupported_1_enc_t0); }
    if !w.write_bool(m.a) { return false; }
    if !match &m.b { Some(v) => w.write_bool(*v), None => true } { return false; }
    true
}

pub proof fn Unsupported_1_enc_pre(v: Unsupported_1)
    requires Unsupported_1_wf()(v),
    ensures Unsupported_1_wf_t0(Unsupported_1_bm(v))(Unsupported_1_tup_t0(v)),
        Unsupported_1_enc()(v) =~= Unsupported_1_bm_enc()(Unsupported_1_bm(v)) + Unsupported_1_enc_t0(Unsupported_1_bm(v))(Unsupported_1_tup_t0(v)),
{
    Unsupported_1_field_bounds(v);
    Unsupported_1_tup0(v);
    assert(Unsupported_1_enc()(v) =~= Unsupported_1_full_enc()(Unsupported_1_from(v)));
}

#[inline]
pub fn Unsupported_1_bm_run(m: &Unsupported_1) -> (bmv: bool)
    ensures bmv == Unsupported_1_bm(Unsupported_1_view(*m)),
{
    proof { reveal(Unsupported_1_bm); }
    m.b.is_some()
}

#[inline]
pub fn Unsupported_1_encode(w: &mut BitWriter, m: &Unsupported_1) -> (ok: bool)
    requires old(w).wf(), Unsupported_1_wf()(Unsupported_1_view(*m)),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Unsupported_1_enc()(Unsupported_1_view(*m)),
{
    proof { Unsupported_1_enc_pre(Unsupported_1_view(*m)); }
    let bmv = Unsupported_1_bm_run(m);
    if !w.write_bool(bmv) { return false; }
    let ok = Unsupported_1_enc_t0_run(w, bmv, m);
    ok
}

#[verifier::external]
#[inline]
pub fn Unsupported_1_jer_members(v: &Unsupported_1, o: &mut String, first: &mut bool) {
    { jer_member("a", first, o); jer_bool(*&v.a, o); }
    if let Some(x) = &v.b { jer_member("b", first, o); jer_bool(*x, o); }
}

#[verifier::external]
#[inline]
pub fn Unsupported_1_jer(v: &Unsupported_1, o: &mut String) {
    o.push('{');
    let mut first = true;
    Unsupported_1_jer_members(v, o, &mut first);
    o.push('}');
}

#[verifier::external]
#[inline]
pub fn Unsupported_1_arb(g: &mut Gen) -> Unsupported_1 {
    Unsupported_1 {
        a: g.bool(),
        b: if g.bool() { Some(g.bool()) } else { None },
    }
}

// ---------------------------------------------------------------- Unsupported-2
pub type Unsupported_2 = Vec<Alpha>;

pub open spec fn Unsupported_2_wf() -> Wf<Seq<Alpha>> { fsized_wf(0, 18446744073709551615, Alpha_wf()) }
pub open spec fn Unsupported_2_enc() -> Enc<Seq<Alpha>> { fsized_enc(Alpha_enc()) }
pub open spec fn Unsupported_2_dec() -> Dec<Seq<Alpha>> { fsized_dec(0, 18446744073709551615, Alpha_dec()) }

pub proof fn Unsupported_2_is_format()
    ensures is_format(Unsupported_2_wf(), Unsupported_2_enc(), Unsupported_2_dec()),
{
    Alpha_is_format();
    lemma_fsized_format(0, 18446744073709551615, Alpha_wf(), Alpha_enc(), Alpha_dec());
}

#[verifier::loop_isolation(false)]
#[inline]
pub fn Unsupported_2_frag_dec(r: &mut BitReader, out_: &mut Vec<Alpha>, c_: u64) -> (res: Option<Flg>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        final(out_)@.len() >= old(out_)@.len(),
        final(out_)@.take(old(out_)@.len() as int) == old(out_)@,
        match res {
            Some(f_) => list_dec_rec(c_ as nat, Alpha_dec(), old(r).rem())
                == Some::<(Seq<Alpha>, nat, Flg)>((final(out_)@.skip(old(out_)@.len() as int),
                                                  (final(r).pos - old(r).pos) as nat, f_)),
            None => list_dec_rec(c_ as nat, Alpha_dec(), old(r).rem()).is_none(),
        },
{
    let ghost body = old(r).rem();
    let ghost p1 = old(r).pos;
    let ghost o0 = out_@;
    let n0 = out_.len();
    let mut i_: u64 = 0;
    let mut fa_: Flg = Flg::SameVer;
    proof {
        lemma_list_loop_start(c_ as nat, Alpha_dec(), body);
        assert(out_@.skip(n0 as int) =~= Seq::<Alpha>::empty());
        assert(out_@.take(n0 as int) =~= o0);
    }
    while i_ < c_
        invariant
            r.wf(), r.buf == old(r).buf, r.pos >= p1, p1 == old(r).pos,
            body == old(r).rem(), o0 == old(out_)@, n0 == o0.len(),
            out_@.len() == n0 + i_, i_ <= c_,
            out_@.take(n0 as int) == o0,
            list_dec_rec(c_ as nat, Alpha_dec(), body)
                == list_cont(out_@.skip(n0 as int), (r.pos - p1) as nat, fa_,
                             list_dec_rec((c_ - i_) as nat, Alpha_dec(), r.rem())),
        decreases c_ - i_,
    {
        let ghost bi = r.rem();
        let ghost pi = r.pos;
        let (x_, fx_) = match Alpha_decode(r) {
            Some(vf_) => vf_,
            None => {
                proof {
                    lemma_list_loop_fail(c_ as nat, Alpha_dec(), body, out_@.skip(n0 as int),
                                         (pi - p1) as nat, fa_, (c_ - i_) as nat, bi);
                }
                let at_: u64 = if n0 as u64 <= u64::MAX - i_ { n0 as u64 + i_ } else { i_ };
                { r.fail_at(at_); return None; }
            }
        };
        let ghost sx_ = x_;
        let ghost all_ = out_@;
        let ghost ov_ = all_.skip(n0 as int);
        proof {
            lemma_rem_skip(r.buf@, pi as nat, (r.pos - pi) as nat);
            lemma_list_loop_step(c_ as nat, Alpha_dec(), body, ov_, (pi - p1) as nat, fa_,
                                 (c_ - i_) as nat, bi, sx_, (r.pos - pi) as nat, fx_);
        }
        out_.push(x_);
        proof {
            assert(out_@ =~= all_.push(sx_));
            assert(out_@.skip(n0 as int) =~= ov_.push(sx_));
            assert(out_@.take(n0 as int) =~= all_.take(n0 as int));
        }
        fa_ = flg_join(fa_, fx_);
        i_ = i_ + 1;
    }
    proof {
        lemma_list_loop_done(c_ as nat, Alpha_dec(), body, out_@.skip(n0 as int),
                             (r.pos - p1) as nat, fa_, r.rem());
    }
    Some(fa_)
}

#[verifier::loop_isolation(false)]
#[inline]
pub fn Unsupported_2_decode(r: &mut BitReader) -> (res: Option<(Unsupported_2, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v_, f_)) => Unsupported_2_dec()(old(r).rem())
                == Some::<(Seq<Alpha>, nat, Flg)>((v_@,
                                                  (final(r).pos - old(r).pos) as nat, f_)),
            None => Unsupported_2_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = old(r).rem();
    let ghost p0 = old(r).pos;
    let mut out_: Vec<Alpha> = Vec::new();
    let mut fa_: Flg = Flg::SameVer;
    let mut pending_: bool = false;
    proof {
        lemma_flist_loop_start(Alpha_dec(), start);
        assert(out_@ =~= Seq::<Alpha>::empty());
        lemma_flist_dec_val(Alpha_dec(), start);
    }
    loop
        invariant
            r.wf(), r.buf == old(r).buf, p0 == old(r).pos, start == old(r).rem(),
            r.pos >= p0,
            r.rem() == start.skip((r.pos - p0) as int),
            (r.pos - p0) + r.rem().len() == start.len(),
            flist_dec(Alpha_dec())(start) == flist_dec_rec(Alpha_dec(), start),
            flist_dec_rec(Alpha_dec(), start)
                == flist_cont(out_@, (r.pos - p0) as nat, fa_, pending_,
                              flist_dec_rec(Alpha_dec(), r.rem())),
        decreases 8 * r.buf@.len() - r.pos,
    {
        let ghost cur = r.rem();
        let ghost consumed = (r.pos - p0) as nat;
        let ghost acc = out_@;
        let ph = r.pos;
        let h = match r.read_lh() {
            Some(h) => h,
            None => {
                proof {
                    lemma_flist_loop_fail(Alpha_dec(), start, cur, acc, consumed, fa_, pending_);
                    lemma_restrict_dec_none(flist_dec(Alpha_dec()), flist_ok(0, 18446744073709551615), start);
                }
                { r.fail("SIZE (0..MAX) length"); return None; }
            }
        };
        proof {
            lemma_lh_dec_facts(cur);
            lemma_lh_wf_iff(h);
            lemma_rem_skip(r.buf@, ph as nat, (r.pos - ph) as nat);
        }
        let ghost k = (r.pos - ph) as nat;
        let (c_, last_) = match h {
            LenHead::Final(n) => (n, true),
            LenHead::Frag(m) => {
                // 11.9.3.8.1: after a fragment below the cap, only a final head
                if pending_ {
                    proof {
                        lemma_flist_loop_pending(Alpha_dec(), start, cur, acc, consumed, fa_, m, k);
                        lemma_restrict_dec_none(flist_dec(Alpha_dec()), flist_ok(0, 18446744073709551615), start);
                    }
                    { r.fail("SIZE (0..MAX) length: fragment after a short fragment"); return None; }
                }
                (m * 16384, false)
            }
        };
        let ghost hm: u64 = match h { LenHead::Final(n) => n, LenHead::Frag(m) => m };
        proof {
            assert(h == if last_ { LenHead::Final(hm) } else { LenHead::Frag(hm) });
            assert(c_ as nat == if last_ { hm as nat } else { (hm as nat) * 16384 });
        }
        let ghost pc = r.pos;
        let fx_ = match Unsupported_2_frag_dec(r, &mut out_, c_) {
            Some(f) => f,
            None => {
                proof {
                    assert(cur.skip(k as int) =~= bits_of(r.buf@).skip(pc as int));
                    lemma_flist_loop_fail(Alpha_dec(), start, cur, acc, consumed, fa_, pending_);
                    lemma_restrict_dec_none(flist_dec(Alpha_dec()), flist_ok(0, 18446744073709551615), start);
                }
                return None;
            }
        };
        let ghost l1 = out_@.skip(acc.len() as int);
        let ghost k1 = (r.pos - pc) as nat;
        proof {
            assert(cur.skip(k as int) =~= bits_of(r.buf@).skip(pc as int));
            assert(out_@ =~= acc + l1);
            lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat);
            assert(k + k1 <= cur.len());
        }
        if last_ {
            proof {
                lemma_flist_loop_final(Alpha_dec(), start, cur, acc, consumed, fa_, pending_,
                                       hm, k, l1, k1, fx_);
            }
            let f_ = flg_join(fa_, fx_);
            let n_ = out_.len();
            if false {
                proof { lemma_restrict_dec_none(flist_dec(Alpha_dec()), flist_ok(0, 18446744073709551615), start); }
                { r.fail("SIZE (0..MAX)"); return None; }
            }
            proof {
                lemma_restrict_dec_some(flist_dec(Alpha_dec()), flist_ok(0, 18446744073709551615), start, out_@,
                                        (r.pos - p0) as nat, f_);
            }
            return Some((out_, f_));
        }
        proof {
            lemma_flist_loop_frag(Alpha_dec(), start, cur, acc, consumed, fa_, hm, k, l1, k1, fx_);
        }
        fa_ = flg_join(fa_, fx_);
        pending_ = c_ < 4 * 16384;
    }
}

#[verifier::loop_isolation(false)]
#[inline]
pub fn Unsupported_2_frag_enc(w: &mut BitWriter, l: &Unsupported_2, from: usize, cnt: usize) -> (ok: bool)
    requires old(w).wf(), from + cnt <= l@.len(),
        forall|i: int| 0 <= i < l@.len() ==> #[trigger] Alpha_wf()(l@[i]),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written()
            =~= old(w).written() + list_enc_rec(l@.subrange(from as int, (from + cnt) as int), Alpha_enc()),
{
    let ghost mid = w.written();
    let n_ = l.len();
    let end_ = from + cnt;
    let mut j_: usize = from;
    proof { assert(l@.subrange(from as int, from as int) =~= Seq::<Alpha>::empty()); }
    while j_ < end_
        invariant
            w.wf(), from <= j_ <= end_, end_ == from + cnt, from + cnt <= l@.len(),
            w.buf@.len() == old(w).buf@.len(),
            w.written() =~= mid + list_enc_rec(l@.subrange(from as int, j_ as int), Alpha_enc()),
        decreases end_ - j_,
    {
        let ghost pre = l@.subrange(from as int, j_ as int);
        let x_ = &l[j_];
        proof { assert(Alpha_wf()(l@[j_ as int])); }
        if !Alpha_encode(w, x_) { return false; }
        proof {
            lemma_list_enc_push(pre, Alpha_enc(), l@[j_ as int]);
            assert(l@.subrange(from as int, j_ as int + 1) =~= pre.push(l@[j_ as int]));
        }
        j_ = j_ + 1;
    }
    true
}

#[verifier::loop_isolation(false)]
#[inline]
pub fn Unsupported_2_encode(w: &mut BitWriter, l: &Unsupported_2) -> (ok: bool)
    requires old(w).wf(), Unsupported_2_wf()(l@),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Unsupported_2_enc()(l@),
{
    let ghost s = l@;
    let ghost w0 = w.written();
    proof {
        lemma_restrict_wf_val(flist_wf(Alpha_wf()), flist_ok(0, 18446744073709551615), s);
        lemma_flist_wf_val(Alpha_wf(), s);
        lemma_flist_enc_val(Alpha_enc(), s);
        assert(s.skip(0) =~= s);
    }
    let n = l.len();
    let mut off: usize = 0;
    while n - off >= 16384
        invariant
            w.wf(), w.buf@.len() == old(w).buf@.len(),
            off <= n, n == l@.len(), s == l@, s.len() == n,
            forall|i: int| 0 <= i < s.len() ==> #[trigger] Alpha_wf()(s[i]),
            w.written() + flist_enc_rec(s.skip(off as int), Alpha_enc()) =~= w0 + flist_enc_rec(s, Alpha_enc()),
        decreases n - off,
    {
        let left = n - off;
        let m: usize = if left / 16384 >= 4 { 4 } else { left / 16384 };
        proof {
            lemma_flist_enc_step(s, Alpha_enc(), off as nat, m as nat);
            lemma_lh_wf_iff(LenHead::Frag(m as u64));
        }
        let ghost before = w.written();
        if !w.write_lh(LenHead::Frag(m as u64)) { return false; }
        if !Unsupported_2_frag_enc(w, l, off, m * 16384) { return false; }
        proof {
            lemma_flist_enc_loop_step(before, w.written(), w0, s, Alpha_enc(), off as nat, m as nat);
        }
        off = off + m * 16384;
    }
    proof {
        lemma_flist_enc_last(s, Alpha_enc(), off as nat);
        lemma_lh_wf_iff(LenHead::Final((n - off) as u64));
    }
    let ghost before = w.written();
    if !w.write_lh(LenHead::Final((n - off) as u64)) { return false; }
    if !Unsupported_2_frag_enc(w, l, off, n - off) { return false; }
    proof {
        lemma_flist_enc_loop_last(before, w.written(), w0, s, Alpha_enc(), off as nat);
    }
    true
}

#[verifier::external]
#[inline]
pub fn Unsupported_2_jer(v: &Unsupported_2, o: &mut String) {
    o.push('[');
    for (i, x) in v.iter().enumerate() {
        if i > 0 { o.push(','); }
        Alpha_jer(x, o);
    }
    o.push(']');
}

#[verifier::external]
#[inline]
pub fn Unsupported_2_arb(g: &mut Gen) -> Unsupported_2 {
    let n = g.len(0, 18446744073709551615);
    (0..n).map(|_| Alpha_arb(g)).collect()
}

} // verus!
