// Generated by vuperc from ASN.1 module `EE-Definitions`. Do not edit.
#![allow(non_snake_case, non_camel_case_types, unused_imports, unused_variables)]
#![allow(bindings_with_variant_name, unused_parens, unused_braces, unused_comparisons, dead_code)]
use vstd::prelude::*;
use vuperx::bitspec::*;
use vuperx::format::*;
use vuperx::prim::*;
use vuperx::term::*;
use vuperx::cursor::*;
use vuperx::opt::*;
use vuperx::list::*;
use vuperx::lendet::*;
use vuperx::frag::*;
use vuperx::fraglist::*;
use vuperx::intx::*;
use vuperx::utf8::*;
use vuperx::opentype::*;
use vuperx::seqext::*;
use vuperx::jer::*;
use vuperx::arb::Gen;

verus! {

broadcast use {format_steps, map_steps, opt_steps, unit_steps, list_steps};

// ---------------------------------------------------------------- RatType (extensible)
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub enum RatType {
    nr,
    eutra_nr,
    eutra,
    utra_fdd_v1610,
}

pub open spec fn RatType_isext(v: RatType) -> bool {
    match v {
        RatType::nr => false,
        RatType::eutra_nr => false,
        RatType::eutra => false,
        RatType::utra_fdd_v1610 => false,
    }
}
pub open spec fn RatType_idx(v: RatType) -> u64 {
    match v {
        RatType::nr => 0u64,
        RatType::eutra_nr => 1u64,
        RatType::eutra => 2u64,
        RatType::utra_fdd_v1610 => 3u64,
    }
}
#[inline]
pub fn RatType_isext_exec(v: &RatType) -> (res: bool)
    ensures res == RatType_isext(*v),
{
    match v {
        RatType::nr => false,
        RatType::eutra_nr => false,
        RatType::eutra => false,
        RatType::utra_fdd_v1610 => false,
    }
}
#[inline]
pub fn RatType_idx_exec(v: &RatType) -> (res: u64)
    ensures res == RatType_idx(*v),
{
    match v {
        RatType::nr => 0u64,
        RatType::eutra_nr => 1u64,
        RatType::eutra => 2u64,
        RatType::utra_fdd_v1610 => 3u64,
    }
}

pub open spec fn RatType_to(t: (bool, u64)) -> RatType {
    let i = t.1;
    if t.0 { RatType::nr } else { if i == 0 { RatType::nr } else { if i == 1 { RatType::eutra_nr } else { if i == 2 { RatType::eutra } else { RatType::utra_fdd_v1610 } } } }
}
pub open spec fn RatType_from(v: RatType) -> (bool, u64) { (RatType_isext(v), RatType_idx(v)) }
pub open spec fn RatType_to_f() -> spec_fn((bool, u64)) -> RatType { |t: (bool, u64)| RatType_to(t) }
pub open spec fn RatType_from_f() -> spec_fn(RatType) -> (bool, u64) { |v: RatType| RatType_from(v) }

#[inline]
pub fn RatType_of(e: bool, i: u64) -> (v: RatType)
    requires if e { i < 0 } else { i <= 3 },
    ensures v == RatType_to((e, i)),
{
    if e { RatType::nr } else { if i == 0 { RatType::nr } else { if i == 1 { RatType::eutra_nr } else { if i == 2 { RatType::eutra } else { RatType::utra_fdd_v1610 } } } }
}

pub open spec fn RatType_ridx_ok() -> spec_fn(u64) -> bool { |i: u64| i <= 3 }
pub open spec fn RatType_ridx_wf() -> Wf<u64> { restrict_wf(uint_wf(2), RatType_ridx_ok()) }
pub open spec fn RatType_ridx_enc() -> Enc<u64> { uint_enc(2) }
pub open spec fn RatType_ridx_dec() -> Dec<u64> { restrict_dec(uint_dec(2), RatType_ridx_ok()) }
pub open spec fn RatType_eidx_ok() -> spec_fn(u64) -> bool { |k: u64| k < 0 }
pub open spec fn RatType_eidx_wf() -> Wf<u64> { restrict_wf(nsn_wf(), RatType_eidx_ok()) }
pub open spec fn RatType_eidx_enc() -> Enc<u64> { nsn_enc() }
pub open spec fn RatType_eidx_dec() -> Dec<u64> { restrict_dec(nsn_dec(), RatType_eidx_ok()) }

pub open spec fn RatType_fam_wf() -> spec_fn(bool) -> Wf<u64> { |e: bool| if e { RatType_eidx_wf() } else { RatType_ridx_wf() } }
pub open spec fn RatType_fam_enc() -> spec_fn(bool) -> Enc<u64> { |e: bool| if e { RatType_eidx_enc() } else { RatType_ridx_enc() } }
pub open spec fn RatType_fam_dec() -> spec_fn(bool) -> Dec<u64> { |e: bool| if e { RatType_eidx_dec() } else { RatType_ridx_dec() } }
pub open spec fn RatType_full_wf() -> Wf<(bool, u64)> { dep_wf(bool_wf(), RatType_fam_wf()) }
pub open spec fn RatType_full_enc() -> Enc<(bool, u64)> { dep_enc(bool_enc(), RatType_fam_enc()) }
pub open spec fn RatType_full_dec() -> Dec<(bool, u64)> { dep_dec(bool_dec(), RatType_fam_dec()) }
pub open spec fn RatType_wf() -> Wf<RatType> { map_wf(RatType_full_wf(), RatType_to_f(), RatType_from_f()) }
pub open spec fn RatType_enc() -> Enc<RatType> { map_enc(RatType_full_enc(), RatType_from_f()) }
pub open spec fn RatType_dec() -> Dec<RatType> { map_dec(RatType_full_dec(), RatType_to_f()) }

pub proof fn RatType_rt_root(i: u64)
    requires RatType_ridx_wf()(i),
    ensures RatType_from(RatType_to((false, i))) == (false, i),
{
}

pub proof fn RatType_rt_ext(i: u64)
    requires RatType_eidx_wf()(i),
    ensures RatType_from(RatType_to((true, i))) == (true, i),
{
}

pub proof fn RatType_is_format()
    ensures is_format(RatType_wf(), RatType_enc(), RatType_dec()),
{
    assert(p2(2) == 4) by { reveal_with_fuel(p2, 4); }
    lemma_uint_format(2);
    lemma_restrict_format(uint_wf(2), uint_enc(2), uint_dec(2), RatType_ridx_ok());
    assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); }
    lemma_nsn_format();
    lemma_restrict_format(nsn_wf(), nsn_enc(), nsn_dec(), RatType_eidx_ok());
    lemma_bool_format();
    assert forall|e: bool| bool_wf()(e) implies
        is_format(#[trigger] RatType_fam_wf()(e), RatType_fam_enc()(e), RatType_fam_dec()(e))
    by { }
    lemma_dep_format(bool_wf(), bool_enc(), bool_dec(),
                     RatType_fam_wf(), RatType_fam_enc(), RatType_fam_dec());
    assert forall|t: (bool, u64)| RatType_full_wf()(t) implies
        #[trigger] RatType_from_f()(RatType_to_f()(t)) == t
    by {
        if t.0 { RatType_rt_ext(t.1); } else { RatType_rt_root(t.1); }
    }
    lemma_map_format(RatType_full_wf(), RatType_full_enc(), RatType_full_dec(),
                     RatType_to_f(), RatType_from_f());
}

#[inline]
pub fn RatType_decode(r: &mut BitReader) -> (res: Option<(RatType, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => RatType_dec()(old(r).rem())
                == Some::<(RatType, nat, Flg)>((v, (final(r).pos - old(r).pos) as nat, f)),
            None => RatType_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let e_ = match r.read_bool() {
        Some(b) => b,
        None => {
            proof {
                lemma_dep_dec_none_fst(bool_dec(), RatType_fam_dec(), start);
                lemma_map_dec_none(RatType_full_dec(), RatType_to_f(), start);
            }
            { r.fail("extension bit"); return None; }
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kb = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let i_ = if e_ {
        proof { assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); } }
        let ghost st = r.rem();
        match r.read_nsn() {
            Some(k) if false => {
                proof { lemma_restrict_dec_some(nsn_dec(), RatType_eidx_ok(), st, k, (r.pos - p1) as nat, Flg::SameVer); }
                k
            }
            _ => {
                proof {
                    lemma_restrict_dec_none(nsn_dec(), RatType_eidx_ok(), st);
                    lemma_dep_dec_none_snd(bool_dec(), RatType_fam_dec(), start, e_, kb, Flg::SameVer);
                lemma_map_dec_none(RatType_full_dec(), RatType_to_f(), start);
                }
                { r.fail("ENUMERATED extension index"); return None; }
            }
        }
    } else {
        proof { assert(p2(2) == 4) by { reveal_with_fuel(p2, 4); } }
        let ghost st = r.rem();
        match r.read_uint(2) {
            Some(i) if i <= 3 => {
                proof { lemma_restrict_dec_some(uint_dec(2), RatType_ridx_ok(), st, i, 2, Flg::SameVer); }
                i
            }
            _ => {
                proof {
                    lemma_restrict_dec_none(uint_dec(2), RatType_ridx_ok(), st);
                    lemma_dep_dec_none_snd(bool_dec(), RatType_fam_dec(), start, e_, kb, Flg::SameVer);
                lemma_map_dec_none(RatType_full_dec(), RatType_to_f(), start);
                }
                { r.fail("ENUMERATED index (0..3)"); return None; }
            }
        }
    };
    proof {
        lemma_dep_dec_some(bool_dec(), RatType_fam_dec(), start, e_, kb, Flg::SameVer,
                           i_, (r.pos - p1) as nat, Flg::SameVer);
        lemma_map_dec_some(RatType_full_dec(), RatType_to_f(), start, (e_, i_),
                           (r.pos - p0) as nat, Flg::SameVer);
    }
    Some((RatType_of(e_, i_), Flg::SameVer))
}

#[inline]
pub fn RatType_encode(w: &mut BitWriter, v: &RatType) -> (ok: bool)
    requires old(w).wf(),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + RatType_enc()(*v),
{
    let e_ = RatType_isext_exec(v);
    let i_ = RatType_idx_exec(v);
    proof { lemma_bool_enc_seq(e_); }
    if !w.write_bool(e_) { return false; }
    if e_ {
        proof { assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); } }
        w.write_nsn(i_)
    } else {
        proof { assert(p2(2) == 4) by { reveal_with_fuel(p2, 4); } }
        w.write_uint(2, i_)
    }
}

#[verifier::external]
#[inline]
pub fn RatType_jer(v: &RatType, o: &mut String) {
    match v {
        RatType::nr => jer_ident("nr", o),
        RatType::eutra_nr => jer_ident("eutra-nr", o),
        RatType::eutra => jer_ident("eutra", o),
        RatType::utra_fdd_v1610 => jer_ident("utra-fdd-v1610", o),
    }
}

#[verifier::external]
#[inline]
pub fn RatType_arb(g: &mut Gen) -> RatType {
    match g.pick(4) {
        0 => RatType::nr,
        1 => RatType::eutra_nr,
        2 => RatType::eutra,
        _ => RatType::utra_fdd_v1610,
    }
}

// ---------------------------------------------------------------- Grown (extensible)
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub enum Grown {
    a,
    b,
    c,
    d_v1700,
    e_v1700,
}

pub open spec fn Grown_isext(v: Grown) -> bool {
    match v {
        Grown::a => false,
        Grown::b => false,
        Grown::c => false,
        Grown::d_v1700 => true,
        Grown::e_v1700 => true,
    }
}
pub open spec fn Grown_idx(v: Grown) -> u64 {
    match v {
        Grown::a => 0u64,
        Grown::b => 1u64,
        Grown::c => 2u64,
        Grown::d_v1700 => 0u64,
        Grown::e_v1700 => 1u64,
    }
}
#[inline]
pub fn Grown_isext_exec(v: &Grown) -> (res: bool)
    ensures res == Grown_isext(*v),
{
    match v {
        Grown::a => false,
        Grown::b => false,
        Grown::c => false,
        Grown::d_v1700 => true,
        Grown::e_v1700 => true,
    }
}
#[inline]
pub fn Grown_idx_exec(v: &Grown) -> (res: u64)
    ensures res == Grown_idx(*v),
{
    match v {
        Grown::a => 0u64,
        Grown::b => 1u64,
        Grown::c => 2u64,
        Grown::d_v1700 => 0u64,
        Grown::e_v1700 => 1u64,
    }
}

pub open spec fn Grown_to(t: (bool, u64)) -> Grown {
    let i = t.1;
    if t.0 { if i == 0 { Grown::d_v1700 } else { Grown::e_v1700 } } else { if i == 0 { Grown::a } else { if i == 1 { Grown::b } else { Grown::c } } }
}
pub open spec fn Grown_from(v: Grown) -> (bool, u64) { (Grown_isext(v), Grown_idx(v)) }
pub open spec fn Grown_to_f() -> spec_fn((bool, u64)) -> Grown { |t: (bool, u64)| Grown_to(t) }
pub open spec fn Grown_from_f() -> spec_fn(Grown) -> (bool, u64) { |v: Grown| Grown_from(v) }

#[inline]
pub fn Grown_of(e: bool, i: u64) -> (v: Grown)
    requires if e { i < 2 } else { i <= 2 },
    ensures v == Grown_to((e, i)),
{
    if e { if i == 0 { Grown::d_v1700 } else { Grown::e_v1700 } } else { if i == 0 { Grown::a } else { if i == 1 { Grown::b } else { Grown::c } } }
}

pub open spec fn Grown_ridx_ok() -> spec_fn(u64) -> bool { |i: u64| i <= 2 }
pub open spec fn Grown_ridx_wf() -> Wf<u64> { restrict_wf(uint_wf(2), Grown_ridx_ok()) }
pub open spec fn Grown_ridx_enc() -> Enc<u64> { uint_enc(2) }
pub open spec fn Grown_ridx_dec() -> Dec<u64> { restrict_dec(uint_dec(2), Grown_ridx_ok()) }
pub open spec fn Grown_eidx_ok() -> spec_fn(u64) -> bool { |k: u64| k < 2 }
pub open spec fn Grown_eidx_wf() -> Wf<u64> { restrict_wf(nsn_wf(), Grown_eidx_ok()) }
pub open spec fn Grown_eidx_enc() -> Enc<u64> { nsn_enc() }
pub open spec fn Grown_eidx_dec() -> Dec<u64> { restrict_dec(nsn_dec(), Grown_eidx_ok()) }

pub open spec fn Grown_fam_wf() -> spec_fn(bool) -> Wf<u64> { |e: bool| if e { Grown_eidx_wf() } else { Grown_ridx_wf() } }
pub open spec fn Grown_fam_enc() -> spec_fn(bool) -> Enc<u64> { |e: bool| if e { Grown_eidx_enc() } else { Grown_ridx_enc() } }
pub open spec fn Grown_fam_dec() -> spec_fn(bool) -> Dec<u64> { |e: bool| if e { Grown_eidx_dec() } else { Grown_ridx_dec() } }
pub open spec fn Grown_full_wf() -> Wf<(bool, u64)> { dep_wf(bool_wf(), Grown_fam_wf()) }
pub open spec fn Grown_full_enc() -> Enc<(bool, u64)> { dep_enc(bool_enc(), Grown_fam_enc()) }
pub open spec fn Grown_full_dec() -> Dec<(bool, u64)> { dep_dec(bool_dec(), Grown_fam_dec()) }
pub open spec fn Grown_wf() -> Wf<Grown> { map_wf(Grown_full_wf(), Grown_to_f(), Grown_from_f()) }
pub open spec fn Grown_enc() -> Enc<Grown> { map_enc(Grown_full_enc(), Grown_from_f()) }
pub open spec fn Grown_dec() -> Dec<Grown> { map_dec(Grown_full_dec(), Grown_to_f()) }

pub proof fn Grown_rt_root(i: u64)
    requires Grown_ridx_wf()(i),
    ensures Grown_from(Grown_to((false, i))) == (false, i),
{
}

pub proof fn Grown_rt_ext(i: u64)
    requires Grown_eidx_wf()(i),
    ensures Grown_from(Grown_to((true, i))) == (true, i),
{
}

pub proof fn Grown_is_format()
    ensures is_format(Grown_wf(), Grown_enc(), Grown_dec()),
{
    assert(p2(2) == 4) by { reveal_with_fuel(p2, 4); }
    lemma_uint_format(2);
    lemma_restrict_format(uint_wf(2), uint_enc(2), uint_dec(2), Grown_ridx_ok());
    assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); }
    lemma_nsn_format();
    lemma_restrict_format(nsn_wf(), nsn_enc(), nsn_dec(), Grown_eidx_ok());
    lemma_bool_format();
    assert forall|e: bool| bool_wf()(e) implies
        is_format(#[trigger] Grown_fam_wf()(e), Grown_fam_enc()(e), Grown_fam_dec()(e))
    by { }
    lemma_dep_format(bool_wf(), bool_enc(), bool_dec(),
                     Grown_fam_wf(), Grown_fam_enc(), Grown_fam_dec());
    assert forall|t: (bool, u64)| Grown_full_wf()(t) implies
        #[trigger] Grown_from_f()(Grown_to_f()(t)) == t
    by {
        if t.0 { Grown_rt_ext(t.1); } else { Grown_rt_root(t.1); }
    }
    lemma_map_format(Grown_full_wf(), Grown_full_enc(), Grown_full_dec(),
                     Grown_to_f(), Grown_from_f());
}

#[inline]
pub fn Grown_decode(r: &mut BitReader) -> (res: Option<(Grown, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Grown_dec()(old(r).rem())
                == Some::<(Grown, nat, Flg)>((v, (final(r).pos - old(r).pos) as nat, f)),
            None => Grown_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let e_ = match r.read_bool() {
        Some(b) => b,
        None => {
            proof {
                lemma_dep_dec_none_fst(bool_dec(), Grown_fam_dec(), start);
                lemma_map_dec_none(Grown_full_dec(), Grown_to_f(), start);
            }
            { r.fail("extension bit"); return None; }
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kb = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let i_ = if e_ {
        proof { assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); } }
        let ghost st = r.rem();
        match r.read_nsn() {
            Some(k) if k < 2 => {
                proof { lemma_restrict_dec_some(nsn_dec(), Grown_eidx_ok(), st, k, (r.pos - p1) as nat, Flg::SameVer); }
                k
            }
            _ => {
                proof {
                    lemma_restrict_dec_none(nsn_dec(), Grown_eidx_ok(), st);
                    lemma_dep_dec_none_snd(bool_dec(), Grown_fam_dec(), start, e_, kb, Flg::SameVer);
                lemma_map_dec_none(Grown_full_dec(), Grown_to_f(), start);
                }
                { r.fail("ENUMERATED extension index"); return None; }
            }
        }
    } else {
        proof { assert(p2(2) == 4) by { reveal_with_fuel(p2, 4); } }
        let ghost st = r.rem();
        match r.read_uint(2) {
            Some(i) if i <= 2 => {
                proof { lemma_restrict_dec_some(uint_dec(2), Grown_ridx_ok(), st, i, 2, Flg::SameVer); }
                i
            }
            _ => {
                proof {
                    lemma_restrict_dec_none(uint_dec(2), Grown_ridx_ok(), st);
                    lemma_dep_dec_none_snd(bool_dec(), Grown_fam_dec(), start, e_, kb, Flg::SameVer);
                lemma_map_dec_none(Grown_full_dec(), Grown_to_f(), start);
                }
                { r.fail("ENUMERATED index (0..2)"); return None; }
            }
        }
    };
    proof {
        lemma_dep_dec_some(bool_dec(), Grown_fam_dec(), start, e_, kb, Flg::SameVer,
                           i_, (r.pos - p1) as nat, Flg::SameVer);
        lemma_map_dec_some(Grown_full_dec(), Grown_to_f(), start, (e_, i_),
                           (r.pos - p0) as nat, Flg::SameVer);
    }
    Some((Grown_of(e_, i_), Flg::SameVer))
}

#[inline]
pub fn Grown_encode(w: &mut BitWriter, v: &Grown) -> (ok: bool)
    requires old(w).wf(),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Grown_enc()(*v),
{
    let e_ = Grown_isext_exec(v);
    let i_ = Grown_idx_exec(v);
    proof { lemma_bool_enc_seq(e_); }
    if !w.write_bool(e_) { return false; }
    if e_ {
        proof { assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); } }
        w.write_nsn(i_)
    } else {
        proof { assert(p2(2) == 4) by { reveal_with_fuel(p2, 4); } }
        w.write_uint(2, i_)
    }
}

#[verifier::external]
#[inline]
pub fn Grown_jer(v: &Grown, o: &mut String) {
    match v {
        Grown::a => jer_ident("a", o),
        Grown::b => jer_ident("b", o),
        Grown::c => jer_ident("c", o),
        Grown::d_v1700 => jer_ident("d-v1700", o),
        Grown::e_v1700 => jer_ident("e-v1700", o),
    }
}

#[verifier::external]
#[inline]
pub fn Grown_arb(g: &mut Gen) -> Grown {
    match g.pick(5) {
        0 => Grown::a,
        1 => Grown::b,
        2 => Grown::c,
        3 => Grown::d_v1700,
        _ => Grown::e_v1700,
    }
}

// ---------------------------------------------------------------- Lone (extensible)
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub enum Lone {
    only,
}

pub open spec fn Lone_isext(v: Lone) -> bool {
    match v {
        Lone::only => false,
    }
}
pub open spec fn Lone_idx(v: Lone) -> u64 {
    match v {
        Lone::only => 0u64,
    }
}
#[inline]
pub fn Lone_isext_exec(v: &Lone) -> (res: bool)
    ensures res == Lone_isext(*v),
{
    match v {
        Lone::only => false,
    }
}
#[inline]
pub fn Lone_idx_exec(v: &Lone) -> (res: u64)
    ensures res == Lone_idx(*v),
{
    match v {
        Lone::only => 0u64,
    }
}

pub open spec fn Lone_to(t: (bool, u64)) -> Lone {
    let i = t.1;
    if t.0 { Lone::only } else { Lone::only }
}
pub open spec fn Lone_from(v: Lone) -> (bool, u64) { (Lone_isext(v), Lone_idx(v)) }
pub open spec fn Lone_to_f() -> spec_fn((bool, u64)) -> Lone { |t: (bool, u64)| Lone_to(t) }
pub open spec fn Lone_from_f() -> spec_fn(Lone) -> (bool, u64) { |v: Lone| Lone_from(v) }

#[inline]
pub fn Lone_of(e: bool, i: u64) -> (v: Lone)
    requires if e { i < 0 } else { i <= 0 },
    ensures v == Lone_to((e, i)),
{
    if e { Lone::only } else { Lone::only }
}

pub open spec fn Lone_ridx_wf() -> Wf<u64> { unit_wf(0u64) }
pub open spec fn Lone_ridx_enc() -> Enc<u64> { unit_enc() }
pub open spec fn Lone_ridx_dec() -> Dec<u64> { unit_dec(0u64) }
pub open spec fn Lone_eidx_ok() -> spec_fn(u64) -> bool { |k: u64| k < 0 }
pub open spec fn Lone_eidx_wf() -> Wf<u64> { restrict_wf(nsn_wf(), Lone_eidx_ok()) }
pub open spec fn Lone_eidx_enc() -> Enc<u64> { nsn_enc() }
pub open spec fn Lone_eidx_dec() -> Dec<u64> { restrict_dec(nsn_dec(), Lone_eidx_ok()) }

pub open spec fn Lone_fam_wf() -> spec_fn(bool) -> Wf<u64> { |e: bool| if e { Lone_eidx_wf() } else { Lone_ridx_wf() } }
pub open spec fn Lone_fam_enc() -> spec_fn(bool) -> Enc<u64> { |e: bool| if e { Lone_eidx_enc() } else { Lone_ridx_enc() } }
pub open spec fn Lone_fam_dec() -> spec_fn(bool) -> Dec<u64> { |e: bool| if e { Lone_eidx_dec() } else { Lone_ridx_dec() } }
pub open spec fn Lone_full_wf() -> Wf<(bool, u64)> { dep_wf(bool_wf(), Lone_fam_wf()) }
pub open spec fn Lone_full_enc() -> Enc<(bool, u64)> { dep_enc(bool_enc(), Lone_fam_enc()) }
pub open spec fn Lone_full_dec() -> Dec<(bool, u64)> { dep_dec(bool_dec(), Lone_fam_dec()) }
pub open spec fn Lone_wf() -> Wf<Lone> { map_wf(Lone_full_wf(), Lone_to_f(), Lone_from_f()) }
pub open spec fn Lone_enc() -> Enc<Lone> { map_enc(Lone_full_enc(), Lone_from_f()) }
pub open spec fn Lone_dec() -> Dec<Lone> { map_dec(Lone_full_dec(), Lone_to_f()) }

pub proof fn Lone_rt_root(i: u64)
    requires Lone_ridx_wf()(i),
    ensures Lone_from(Lone_to((false, i))) == (false, i),
{
}

pub proof fn Lone_rt_ext(i: u64)
    requires Lone_eidx_wf()(i),
    ensures Lone_from(Lone_to((true, i))) == (true, i),
{
}

pub proof fn Lone_is_format()
    ensures is_format(Lone_wf(), Lone_enc(), Lone_dec()),
{
    lemma_unit_format(0u64);
    assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); }
    lemma_nsn_format();
    lemma_restrict_format(nsn_wf(), nsn_enc(), nsn_dec(), Lone_eidx_ok());
    lemma_bool_format();
    assert forall|e: bool| bool_wf()(e) implies
        is_format(#[trigger] Lone_fam_wf()(e), Lone_fam_enc()(e), Lone_fam_dec()(e))
    by { }
    lemma_dep_format(bool_wf(), bool_enc(), bool_dec(),
                     Lone_fam_wf(), Lone_fam_enc(), Lone_fam_dec());
    assert forall|t: (bool, u64)| Lone_full_wf()(t) implies
        #[trigger] Lone_from_f()(Lone_to_f()(t)) == t
    by {
        if t.0 { Lone_rt_ext(t.1); } else { Lone_rt_root(t.1); }
    }
    lemma_map_format(Lone_full_wf(), Lone_full_enc(), Lone_full_dec(),
                     Lone_to_f(), Lone_from_f());
}

#[inline]
pub fn Lone_decode(r: &mut BitReader) -> (res: Option<(Lone, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Lone_dec()(old(r).rem())
                == Some::<(Lone, nat, Flg)>((v, (final(r).pos - old(r).pos) as nat, f)),
            None => Lone_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let e_ = match r.read_bool() {
        Some(b) => b,
        None => {
            proof {
                lemma_dep_dec_none_fst(bool_dec(), Lone_fam_dec(), start);
                lemma_map_dec_none(Lone_full_dec(), Lone_to_f(), start);
            }
            { r.fail("extension bit"); return None; }
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kb = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let i_ = if e_ {
        proof { assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); } }
        let ghost st = r.rem();
        match r.read_nsn() {
            Some(k) if false => {
                proof { lemma_restrict_dec_some(nsn_dec(), Lone_eidx_ok(), st, k, (r.pos - p1) as nat, Flg::SameVer); }
                k
            }
            _ => {
                proof {
                    lemma_restrict_dec_none(nsn_dec(), Lone_eidx_ok(), st);
                    lemma_dep_dec_none_snd(bool_dec(), Lone_fam_dec(), start, e_, kb, Flg::SameVer);
                lemma_map_dec_none(Lone_full_dec(), Lone_to_f(), start);
                }
                { r.fail("ENUMERATED extension index"); return None; }
            }
        }
    } else {
        proof { lemma_unit_dec_val(0u64, r.rem()); }
        0u64
    };
    proof {
        lemma_dep_dec_some(bool_dec(), Lone_fam_dec(), start, e_, kb, Flg::SameVer,
                           i_, (r.pos - p1) as nat, Flg::SameVer);
        lemma_map_dec_some(Lone_full_dec(), Lone_to_f(), start, (e_, i_),
                           (r.pos - p0) as nat, Flg::SameVer);
    }
    Some((Lone_of(e_, i_), Flg::SameVer))
}

#[inline]
pub fn Lone_encode(w: &mut BitWriter, v: &Lone) -> (ok: bool)
    requires old(w).wf(),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Lone_enc()(*v),
{
    let e_ = Lone_isext_exec(v);
    let i_ = Lone_idx_exec(v);
    proof { lemma_bool_enc_seq(e_); }
    if !w.write_bool(e_) { return false; }
    if e_ {
        proof { assert(p2(7) == 128) by { reveal_with_fuel(p2, 9); } }
        w.write_nsn(i_)
    } else {
        proof { assert(w.written() + unit_enc::<u64>()(i_) =~= w.written()); }
        true
    }
}

#[verifier::external]
#[inline]
pub fn Lone_jer(v: &Lone, o: &mut String) {
    match v {
        Lone::only => jer_ident("only", o),
    }
}

#[verifier::external]
#[inline]
pub fn Lone_arb(g: &mut Gen) -> Lone {
    match g.pick(1) {
        _ => Lone::only,
    }
}

// ---------------------------------------------------------------- Plain
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub enum Plain {
    x,
    y,
}

pub open spec fn Plain_to(v: u64) -> Plain {
    if v == 0 { Plain::x } else {
    Plain::y
    }
}

pub open spec fn Plain_from(e: Plain) -> u64 {
    match e {
        Plain::x => 0,
        Plain::y => 1,
    }
}

pub open spec fn Plain_ok() -> spec_fn(u64) -> bool { |v: u64| v <= 1 }
pub open spec fn Plain_to_f() -> spec_fn(u64) -> Plain { |v: u64| Plain_to(v) }
pub open spec fn Plain_from_f() -> spec_fn(Plain) -> u64 { |e: Plain| Plain_from(e) }
pub open spec fn Plain_base_wf() -> Wf<u64> { restrict_wf(uint_wf(1), Plain_ok()) }
pub open spec fn Plain_base_dec() -> Dec<u64> { restrict_dec(uint_dec(1), Plain_ok()) }
pub open spec fn Plain_wf() -> Wf<Plain> { map_wf(Plain_base_wf(), Plain_to_f(), Plain_from_f()) }
pub open spec fn Plain_enc() -> Enc<Plain> { map_enc(uint_enc(1), Plain_from_f()) }
pub open spec fn Plain_dec() -> Dec<Plain> { map_dec(Plain_base_dec(), Plain_to_f()) }

pub proof fn Plain_is_format()
    ensures is_format(Plain_wf(), Plain_enc(), Plain_dec()),
{
    lemma_uint_format(1);
    lemma_restrict_format(uint_wf(1), uint_enc(1), uint_dec(1), Plain_ok());
    assert forall|v: u64| Plain_base_wf()(v) implies
        #[trigger] Plain_from_f()(Plain_to_f()(v)) == v by { }
    lemma_map_format(Plain_base_wf(), uint_enc(1), Plain_base_dec(),
                     Plain_to_f(), Plain_from_f());
}

#[inline]
pub fn Plain_of_u64(v: u64) -> (e: Plain)
    requires v <= 1,
    ensures e == Plain_to(v),
{
    if v == 0 { Plain::x } else {
    Plain::y
    }
}

#[inline]
pub fn Plain_as_u64(e: &Plain) -> (v: u64)
    ensures v == Plain_from(*e),
{
    match e {
        Plain::x => 0,
        Plain::y => 1,
    }
}

#[inline]
pub fn Plain_decode(r: &mut BitReader) -> (res: Option<(Plain, Flg)>)
    requires old(r).wf(),
    ensures
        final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Plain_dec()(old(r).rem())
                == Some::<(Plain, nat, Flg)>((v,
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => Plain_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    match r.read_uint(1) {
        Some(v) => if v <= 1 {
            proof {
                lemma_restrict_dec_some(uint_dec(1), Plain_ok(), start, v, 1, Flg::SameVer);
                lemma_map_dec_some(Plain_base_dec(), Plain_to_f(), start, v, 1, Flg::SameVer);
            }
            Some((Plain_of_u64(v), Flg::SameVer))
        } else {
            proof {
                lemma_restrict_dec_none(uint_dec(1), Plain_ok(), start);
                lemma_map_dec_none(Plain_base_dec(), Plain_to_f(), start);
            }
            { r.fail("ENUMERATED index (0..1)"); None }
        },
        None => {
            proof {
                lemma_restrict_dec_none(uint_dec(1), Plain_ok(), start);
                lemma_map_dec_none(Plain_base_dec(), Plain_to_f(), start);
            }
            { r.fail("ENUMERATED index (0..1)"); None }
        }
    }
}

#[inline]
pub fn Plain_encode(w: &mut BitWriter, e: &Plain) -> (ok: bool)
    requires old(w).wf(),
    ensures
        final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Plain_enc()(*e),
{
    let v = Plain_as_u64(e);
    proof { assert(uint_wf(1 as nat)(v)) by { reveal_with_fuel(p2, 3); } }
    w.write_uint(1, v)
}

#[verifier::external]
#[inline]
pub fn Plain_jer(v: &Plain, o: &mut String) {
    match v {
        Plain::x => jer_ident("x", o),
        Plain::y => jer_ident("y", o),
    }
}

#[verifier::external]
#[inline]
pub fn Plain_arb(g: &mut Gen) -> Plain {
    match g.pick(2) {
        0 => Plain::x,
        _ => Plain::y,
    }
}

// ---------------------------------------------------------------- Holder
#[derive(PartialEq, Eq, Clone, Copy, Debug, Structural)]
pub struct Holder {
    pub rat: RatType,
    pub grown: Option<Grown>,
    pub lone: Lone,
    pub plain: Plain,
}

pub open spec fn Holder_view(m: Holder) -> Holder { m }

pub type Holder_T2 = (Lone, Plain);
pub type Holder_ET2 = (Lone, Plain);
pub type Holder_T1 = (RatType, Option<Grown>);
pub type Holder_ET1 = (RatType, Option<Grown>);
pub type Holder_T0 = (Holder_T1, Holder_T2);
pub type Holder_ET0 = (Holder_ET1, Holder_ET2);
pub open spec fn Holder_view_t2(v: Holder_ET2) -> Holder_T2 { (v.0, v.1) }
pub open spec fn Holder_view_t1(v: Holder_ET1) -> Holder_T1 { (v.0, v.1) }
pub open spec fn Holder_view_t0(v: Holder_ET0) -> Holder_T0 { (Holder_view_t1(v.0), Holder_view_t2(v.1)) }
#[verifier::opaque]
pub open spec fn Holder_tup_t2(m: Holder) -> Holder_T2 { (m.lone, m.plain) }
#[verifier::opaque]
pub open spec fn Holder_tup_t1(m: Holder) -> Holder_T1 { (m.rat, m.grown) }
#[verifier::opaque]
pub open spec fn Holder_tup_t0(m: Holder) -> Holder_T0 { (Holder_tup_t1(m), Holder_tup_t2(m)) }

pub open spec fn Holder_bm_wf() -> Wf<bool> { bool_wf() }
pub open spec fn Holder_bm_enc() -> Enc<bool> { bool_enc() }
pub open spec fn Holder_bm_dec() -> Dec<bool> { bool_dec() }

pub proof fn Holder_bm_is_format()
    ensures is_format(Holder_bm_wf(), Holder_bm_enc(), Holder_bm_dec()),
{
    lemma_bool_format();
}

pub open spec fn Holder_to(t: (bool, Holder_T0)) -> Holder {
    Holder {
        rat: t.1.0.0,
        grown: t.1.0.1,
        lone: t.1.1.0,
        plain: t.1.1.1,
    }
}

pub open spec fn Holder_body(m: Holder) -> Holder_T0 { ((m.rat, m.grown), (m.lone, m.plain)) }
#[verifier::opaque]
pub open spec fn Holder_bm(m: Holder) -> bool { m.grown is Some }
pub open spec fn Holder_from(m: Holder) -> (bool, Holder_T0) { (Holder_bm(m), Holder_body(m)) }
pub open spec fn Holder_to_f() -> spec_fn((bool, Holder_T0)) -> Holder { |t: (bool, Holder_T0)| Holder_to(t) }
pub open spec fn Holder_from_f() -> spec_fn(Holder) -> (bool, Holder_T0) { |m: Holder| Holder_from(m) }

pub proof fn Holder_tup0(m: Holder)
    ensures Holder_tup_t0(m) == Holder_body(m),
{
    reveal(Holder_tup_t0);
    reveal(Holder_tup_t1);
    reveal(Holder_tup_t2);
}

#[verifier::opaque]
pub open spec fn Holder_wf_t2(bm: bool) -> Wf<Holder_T2> { pair_wf(Lone_wf(), Plain_wf()) }
#[verifier::opaque]
pub open spec fn Holder_enc_t2(bm: bool) -> Enc<Holder_T2> { pair_enc(Lone_enc(), Plain_enc()) }
#[verifier::opaque]
pub open spec fn Holder_dec_t2(bm: bool) -> Dec<Holder_T2> { pair_dec(Lone_dec(), Plain_dec()) }
#[verifier::opaque]
pub open spec fn Holder_wf_t1(bm: bool) -> Wf<Holder_T1> { pair_wf(RatType_wf(), opt_wf(bm, Grown_wf())) }
#[verifier::opaque]
pub open spec fn Holder_enc_t1(bm: bool) -> Enc<Holder_T1> { pair_enc(RatType_enc(), opt_enc(bm, Grown_enc())) }
#[verifier::opaque]
pub open spec fn Holder_dec_t1(bm: bool) -> Dec<Holder_T1> { pair_dec(RatType_dec(), opt_dec(bm, Grown_dec())) }
#[verifier::opaque]
pub open spec fn Holder_wf_t0(bm: bool) -> Wf<Holder_T0> { pair_wf(Holder_wf_t1(bm), Holder_wf_t2(bm)) }
#[verifier::opaque]
pub open spec fn Holder_enc_t0(bm: bool) -> Enc<Holder_T0> { pair_enc(Holder_enc_t1(bm), Holder_enc_t2(bm)) }
#[verifier::opaque]
pub open spec fn Holder_dec_t0(bm: bool) -> Dec<Holder_T0> { pair_dec(Holder_dec_t1(bm), Holder_dec_t2(bm)) }

pub open spec fn Holder_body_wf() -> spec_fn(bool) -> Wf<Holder_T0> { |bm: bool| Holder_wf_t0(bm) }
pub open spec fn Holder_body_enc() -> spec_fn(bool) -> Enc<Holder_T0> { |bm: bool| Holder_enc_t0(bm) }
pub open spec fn Holder_body_dec() -> spec_fn(bool) -> Dec<Holder_T0> { |bm: bool| Holder_dec_t0(bm) }

pub open spec fn Holder_full_wf() -> Wf<(bool, Holder_T0)> { dep_wf(Holder_bm_wf(), Holder_body_wf()) }
pub open spec fn Holder_full_enc() -> Enc<(bool, Holder_T0)> { dep_enc(Holder_bm_enc(), Holder_body_enc()) }
pub open spec fn Holder_full_dec() -> Dec<(bool, Holder_T0)> { dep_dec(Holder_bm_dec(), Holder_body_dec()) }

pub open spec fn Holder_wf() -> Wf<Holder> { map_wf(Holder_full_wf(), Holder_to_f(), Holder_from_f()) }
pub open spec fn Holder_enc() -> Enc<Holder> { map_enc(Holder_full_enc(), Holder_from_f()) }
pub open spec fn Holder_dec() -> Dec<Holder> { map_dec(Holder_full_dec(), Holder_to_f()) }

pub proof fn Holder_body_is_format_t2(bm: bool)
    ensures is_format(Holder_wf_t2(bm), Holder_enc_t2(bm), Holder_dec_t2(bm)),
{
    reveal(Holder_wf_t2); reveal(Holder_enc_t2); reveal(Holder_dec_t2);
    Lone_is_format();
    Plain_is_format();
    lemma_pair_format(Lone_wf(), Lone_enc(), Lone_dec(), Plain_wf(), Plain_enc(), Plain_dec());
}

pub proof fn Holder_body_is_format_t1(bm: bool)
    ensures is_format(Holder_wf_t1(bm), Holder_enc_t1(bm), Holder_dec_t1(bm)),
{
    reveal(Holder_wf_t1); reveal(Holder_enc_t1); reveal(Holder_dec_t1);
    RatType_is_format();
    Grown_is_format();
    lemma_opt_format(bm, Grown_wf(), Grown_enc(), Grown_dec());
    lemma_pair_format(RatType_wf(), RatType_enc(), RatType_dec(), opt_wf(bm, Grown_wf()), opt_enc(bm, Grown_enc()), opt_dec(bm, Grown_dec()));
}

pub proof fn Holder_body_is_format_t0(bm: bool)
    ensures is_format(Holder_wf_t0(bm), Holder_enc_t0(bm), Holder_dec_t0(bm)),
{
    reveal(Holder_wf_t0); reveal(Holder_enc_t0); reveal(Holder_dec_t0);
    Holder_body_is_format_t1(bm);
    Holder_body_is_format_t2(bm);
    lemma_pair_format(Holder_wf_t1(bm), Holder_enc_t1(bm), Holder_dec_t1(bm), Holder_wf_t2(bm), Holder_enc_t2(bm), Holder_dec_t2(bm));
}

pub proof fn Holder_body_is_format(bm: bool)
    ensures is_format(Holder_wf_t0(bm), Holder_enc_t0(bm), Holder_dec_t0(bm)),
{
    Holder_body_is_format_t0(bm);
}

pub proof fn Holder_bits_t1(bm: bool, t: Holder_T1)
    requires Holder_wf_t1(bm)(t),
    ensures
        (t.1 is Some) == bm,
{
    reveal(Holder_wf_t1);
    lemma_pair_wf_val(RatType_wf(), opt_wf(bm, Grown_wf()), t.0, t.1);
    assert(t == (t.0, t.1));
}

pub proof fn Holder_bits_t0(bm: bool, t: Holder_T0)
    requires Holder_wf_t0(bm)(t),
    ensures
        (t.0.1 is Some) == bm,
{
    reveal(Holder_wf_t0);
    lemma_pair_wf_val(Holder_wf_t1(bm), Holder_wf_t2(bm), t.0, t.1);
    assert(t == (t.0, t.1));
    Holder_bits_t1(bm, t.0);
}

pub proof fn Holder_rt(t: (bool, Holder_T0))
    requires Holder_full_wf()(t),
    ensures Holder_from_f()(Holder_to_f()(t)) == t,
{
    reveal(Holder_bm);
    Holder_bits_t0(t.0, t.1);
}

pub proof fn Holder_is_format()
    ensures is_format(Holder_wf(), Holder_enc(), Holder_dec()),
{
    Holder_bm_is_format();
    assert forall|bm: bool| Holder_bm_wf()(bm) implies
        is_format(#[trigger] Holder_body_wf()(bm), Holder_body_enc()(bm), Holder_body_dec()(bm))
    by { Holder_body_is_format(bm); }
    lemma_dep_format(Holder_bm_wf(), Holder_bm_enc(), Holder_bm_dec(),
                     Holder_body_wf(), Holder_body_enc(), Holder_body_dec());
    assert forall|t: (bool, Holder_T0)| Holder_full_wf()(t) implies
        #[trigger] Holder_from_f()(Holder_to_f()(t)) == t by { Holder_rt(t); }
    lemma_map_format(Holder_full_wf(), Holder_full_enc(), Holder_full_dec(),
                     Holder_to_f(), Holder_from_f());
}

pub proof fn Holder_field_bounds(v: Holder)
    requires Holder_wf()(v),
    ensures Holder_full_wf()(Holder_from(v)),
{
    assert(Holder_from_f()(Holder_to_f()(Holder_from(v))) == Holder_from(v));
}

#[inline]
pub fn Holder_f1_run(r: &mut BitReader, present: bool) -> (res: Option<(Option<Grown>, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => opt_dec(present, Grown_dec())(old(r).rem())
                == Some::<(Option<Grown>, nat, Flg)>((v,
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => opt_dec(present, Grown_dec())(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    if present {
        match Grown_decode(r) {
            Some((v, f)) => {
                proof { lemma_opt_dec_some(Grown_enc(), Grown_dec(), start, v,
                                           (r.pos - p0) as nat, f); }
                Some((Some(v), f))
            }
            None => {
                proof { lemma_opt_dec_fail(Grown_dec(), start); }
                None
            }
        }
    } else {
        proof { lemma_opt_dec_absent(Grown_dec(), start); }
        Some((None, Flg::SameVer))
    }
}

#[inline]
pub fn Holder_dec_t2_run(r: &mut BitReader, bm: bool) -> (res: Option<(Holder_ET2, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Holder_dec_t2(bm)(old(r).rem())
                == Some::<(Holder_T2, nat, Flg)>((Holder_view_t2(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => Holder_dec_t2(bm)(old(r).rem()).is_none(),
        },
{
    proof { reveal(Holder_dec_t2); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match Lone_decode(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(Lone_dec(), Plain_dec(), start); }
            r.fail_in("lone"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match Plain_decode(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(Lone_dec(), Plain_dec(), start, head, kh, fh); }
            r.fail_in("plain"); return None;
        }
    };
    proof { lemma_pair_dec_some(Lone_dec(), Plain_dec(), start, head, kh, fh, tail,
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn Holder_dec_t1_run(r: &mut BitReader, bm: bool) -> (res: Option<(Holder_ET1, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Holder_dec_t1(bm)(old(r).rem())
                == Some::<(Holder_T1, nat, Flg)>((Holder_view_t1(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => Holder_dec_t1(bm)(old(r).rem()).is_none(),
        },
{
    proof { reveal(Holder_dec_t1); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match RatType_decode(r) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(RatType_dec(), opt_dec(bm, Grown_dec()), start); }
            r.fail_in("rat"); return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match Holder_f1_run(r, bm) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(RatType_dec(), opt_dec(bm, Grown_dec()), start, head, kh, fh); }
            r.fail_in("grown"); return None;
        }
    };
    proof { lemma_pair_dec_some(RatType_dec(), opt_dec(bm, Grown_dec()), start, head, kh, fh, tail,
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn Holder_dec_t0_run(r: &mut BitReader, bm: bool) -> (res: Option<(Holder_ET0, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Holder_dec_t0(bm)(old(r).rem())
                == Some::<(Holder_T0, nat, Flg)>((Holder_view_t0(v),
                                     (final(r).pos - old(r).pos) as nat, f)),
            None => Holder_dec_t0(bm)(old(r).rem()).is_none(),
        },
{
    proof { reveal(Holder_dec_t0); }
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let (head, fh) = match Holder_dec_t1_run(r, bm) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_fst(Holder_dec_t1(bm), Holder_dec_t2(bm), start); }
             return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kh = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (tail, ft) = match Holder_dec_t2_run(r, bm) {
        Some(vf) => vf,
        None => {
            proof { lemma_pair_dec_none_snd(Holder_dec_t1(bm), Holder_dec_t2(bm), start, Holder_view_t1(head), kh, fh); }
             return None;
        }
    };
    proof { lemma_pair_dec_some(Holder_dec_t1(bm), Holder_dec_t2(bm), start, Holder_view_t1(head), kh, fh, Holder_view_t2(tail),
                                (r.pos - p1) as nat, ft); }
    Some(((head, tail), flg_join(fh, ft)))
}

#[inline]
pub fn Holder_decode(r: &mut BitReader) -> (res: Option<(Holder, Flg)>)
    requires old(r).wf(),
    ensures final(r).wf(), final(r).buf == old(r).buf, final(r).pos >= old(r).pos,
        match res {
            Some((v, f)) => Holder_dec()(old(r).rem())
                == Some::<(Holder, nat, Flg)>((Holder_view(v),
                                         (final(r).pos - old(r).pos) as nat, f)),
            None => Holder_dec()(old(r).rem()).is_none(),
        },
{
    let ghost start = r.rem();
    let ghost p0 = r.pos;
    let bm = match { let o_ = r.read_bool(); r.got(o_, "preamble") } {
        Some(v) => v,
        None => {
            proof {
                lemma_dep_dec_none_fst(Holder_bm_dec(), Holder_body_dec(), start);
                lemma_map_dec_none(Holder_full_dec(), Holder_to_f(), start);
            }
            return None;
        }
    };
    proof { lemma_rem_skip(r.buf@, p0 as nat, (r.pos - p0) as nat); }
    let ghost kbm = (r.pos - p0) as nat;
    let ghost p1 = r.pos;
    let (body, fb) = match Holder_dec_t0_run(r, bm) {
        Some(vf) => vf,
        None => {
            proof {
                lemma_dep_dec_none_snd(Holder_bm_dec(), Holder_body_dec(), start, bm, kbm,
                                      Flg::SameVer);
                lemma_map_dec_none(Holder_full_dec(), Holder_to_f(), start);
            }
             return None;
        }
    };
    proof {
        lemma_dep_dec_some(Holder_bm_dec(), Holder_body_dec(), start, bm, kbm, Flg::SameVer,
                           Holder_view_t0(body), (r.pos - p1) as nat, fb);
        lemma_map_dec_some(Holder_full_dec(), Holder_to_f(), start, (bm, Holder_view_t0(body)),
                           (r.pos - p0) as nat, fb);
    }
    Some((Holder { rat: body.0.0, grown: body.0.1, lone: body.1.0, plain: body.1.1, }, fb))
}

#[inline]
pub fn Holder_enc_t2_run(w: &mut BitWriter, bm: bool, m: &Holder) -> (ok: bool)
    requires old(w).wf(), Holder_wf_t2(bm)(Holder_tup_t2(Holder_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Holder_enc_t2(bm)(Holder_tup_t2(Holder_view(*m))),
{
    proof { reveal(Holder_tup_t2); reveal(Holder_wf_t2); reveal(Holder_enc_t2); }
    if !Lone_encode(w, &m.lone) { return false; }
    if !Plain_encode(w, &m.plain) { return false; }
    true
}

#[inline]
pub fn Holder_enc_t1_run(w: &mut BitWriter, bm: bool, m: &Holder) -> (ok: bool)
    requires old(w).wf(), Holder_wf_t1(bm)(Holder_tup_t1(Holder_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Holder_enc_t1(bm)(Holder_tup_t1(Holder_view(*m))),
{
    proof { reveal(Holder_tup_t1); reveal(Holder_wf_t1); reveal(Holder_enc_t1); }
    if !RatType_encode(w, &m.rat) { return false; }
    if !match &m.grown { Some(v) => Grown_encode(w, v), None => true } { return false; }
    true
}

#[inline]
pub fn Holder_enc_t0_run(w: &mut BitWriter, bm: bool, m: &Holder) -> (ok: bool)
    requires old(w).wf(), Holder_wf_t0(bm)(Holder_tup_t0(Holder_view(*m))),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Holder_enc_t0(bm)(Holder_tup_t0(Holder_view(*m))),
{
    proof { reveal(Holder_tup_t0); reveal(Holder_wf_t0); reveal(Holder_enc_t0); }
    if !Holder_enc_t1_run(w, bm, m) { return false; }
    if !Holder_enc_t2_run(w, bm, m) { return false; }
    true
}

pub proof fn Holder_enc_pre(v: Holder)
    requires Holder_wf()(v),
    ensures Holder_wf_t0(Holder_bm(v))(Holder_tup_t0(v)),
        Holder_enc()(v) =~= Holder_bm_enc()(Holder_bm(v)) + Holder_enc_t0(Holder_bm(v))(Holder_tup_t0(v)),
{
    Holder_field_bounds(v);
    Holder_tup0(v);
    assert(Holder_enc()(v) =~= Holder_full_enc()(Holder_from(v)));
}

#[inline]
pub fn Holder_bm_run(m: &Holder) -> (bmv: bool)
    ensures bmv == Holder_bm(Holder_view(*m)),
{
    proof { reveal(Holder_bm); }
    m.grown.is_some()
}

#[inline]
pub fn Holder_encode(w: &mut BitWriter, m: &Holder) -> (ok: bool)
    requires old(w).wf(), Holder_wf()(Holder_view(*m)),
    ensures final(w).wf(), final(w).buf@.len() == old(w).buf@.len(),
        ok ==> final(w).written() =~= old(w).written() + Holder_enc()(Holder_view(*m)),
{
    proof { Holder_enc_pre(Holder_view(*m)); }
    let bmv = Holder_bm_run(m);
    if !w.write_bool(bmv) { return false; }
    let ok = Holder_enc_t0_run(w, bmv, m);
    ok
}

#[verifier::external]
#[inline]
pub fn Holder_jer_members(v: &Holder, o: &mut String, first: &mut bool) {
    { jer_member("rat", first, o); RatType_jer(&v.rat, o); }
    if let Some(x) = &v.grown { jer_member("grown", first, o); Grown_jer(x, o); }
    { jer_member("lone", first, o); Lone_jer(&v.lone, o); }
    { jer_member("plain", first, o); Plain_jer(&v.plain, o); }
}

#[verifier::external]
#[inline]
pub fn Holder_jer(v: &Holder, o: &mut String) {
    o.push('{');
    let mut first = true;
    Holder_jer_members(v, o, &mut first);
    o.push('}');
}

#[verifier::external]
#[inline]
pub fn Holder_arb(g: &mut Gen) -> Holder {
    Holder {
        rat: RatType_arb(g),
        grown: if g.bool() { Some(Grown_arb(g)) } else { None },
        lone: Lone_arb(g),
        plain: Plain_arb(g),
    }
}

} // verus!
